---
version: 3

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/awx-ee:latest'

dependencies:
  galaxy:
    collections:
      - kubernetes.core

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append: |
    RUN pip3 install kubernetes 