---
- name: 备份 AWX 配置
  hosts: KS-1
  gather_facts: yes
  vars:
    backup_dir: "/backup/awx"
    timestamp: "{{ ansible_date_time.date }}"
    awx_cli: "/usr/bin/awx"
    awx_host: "http://localhost"
    awx_username: "admin"
    awx_password: "{{ lookup('env', 'AWX_PASSWORD') }}"
    pg_container: "awx_postgres"
    pg_database: "awx"
  
  tasks:
    - name: 检查 AWX CLI 是否存在
      stat:
        path: "{{ awx_cli }}"
      register: awx_cli_stat
      become: yes

    - name: 如果找不到 AWX CLI，尝试安装
      when: not awx_cli_stat.stat.exists
      block:
        - name: 安装 AWX CLI
          shell: |
            python3 -m pip install --user awxkit
          become: yes

        - name: 创建 AWX CLI 链接
          shell: |
            ln -sf /root/.local/bin/awx {{ awx_cli }}
          become: yes

    - name: 创建备份目录
      file:
        path: "{{ backup_dir }}/{{ timestamp }}"
        state: directory
        mode: '0755'
      become: yes

    - name: 备份 PostgreSQL 数据库
      shell: |
        k3s kubectl exec -n awx {{ pg_container }} -- pg_dump -U awx {{ pg_database }} > {{ backup_dir }}/{{ timestamp }}/awx_db.sql
      register: pg_result
      become: yes

    - name: 备份 AWX 配置文件
      shell: |
        k3s kubectl cp awx/{{ pg_container }}:/var/lib/postgresql/data/postgresql.conf {{ backup_dir }}/{{ timestamp }}/postgresql.conf
        k3s kubectl cp awx/{{ pg_container }}:/var/lib/postgresql/data/pg_hba.conf {{ backup_dir }}/{{ timestamp }}/pg_hba.conf
      register: pg_conf_result
      become: yes

    - name: 备份组织配置
      shell: |
        {{ awx_cli }} organization list --format json > {{ backup_dir }}/{{ timestamp }}/organizations.json
      register: org_result
      become: yes

    - name: 备份项目配置
      shell: |
        {{ awx_cli }} project list --format json > {{ backup_dir }}/{{ timestamp }}/projects.json
      register: proj_result
      become: yes

    - name: 备份模板配置
      shell: |
        {{ awx_cli }} job_template list --format json > {{ backup_dir }}/{{ timestamp }}/templates.json
      register: temp_result
      become: yes

    - name: 备份清单配置
      shell: |
        {{ awx_cli }} inventory list --format json > {{ backup_dir }}/{{ timestamp }}/inventories.json
      register: inv_result
      become: yes

    - name: 备份凭据配置
      shell: |
        {{ awx_cli }} credential list --format json > {{ backup_dir }}/{{ timestamp }}/credentials.json
      register: cred_result
      become: yes

    - name: 压缩备份文件
      shell: |
        cd {{ backup_dir }} && tar -czf awx-backup-{{ timestamp }}.tar.gz {{ timestamp }}
      args:
        warn: false
      become: yes

    - name: 清理临时文件
      file:
        path: "{{ backup_dir }}/{{ timestamp }}"
        state: absent
      become: yes

    - name: 删除超过 7 天的备份
      shell: |
        find {{ backup_dir }} -name "awx-backup-*.tar.gz" -mtime +7 -delete
      become: yes 