---
- name: 恢复 AWX 配置
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    backup_dir: "/backup/awx"
    backup_file: "{{ backup_file | default('') }}"
    temp_dir: "/tmp/awx-restore"
    awx_cli: "awx"
  
  tasks:
    - name: 检查备份文件是否指定
      fail:
        msg: "请指定要恢复的备份文件，例如: -e backup_file=awx-backup-2025-01-26.tar.gz"
      when: backup_file == ''

    - name: 创建临时目录
      file:
        path: "{{ temp_dir }}"
        state: directory
        mode: '0755'

    - name: 解压备份文件
      unarchive:
        src: "{{ backup_dir }}/{{ backup_file }}"
        dest: "{{ temp_dir }}"
        remote_src: yes

    - name: 获取备份日期
      shell: |
        ls {{ temp_dir }} | head -n 1
      register: backup_date

    - name: 恢复组织配置
      shell: |
        cat {{ temp_dir }}/{{ backup_date.stdout }}/organizations.json | {{ awx_cli }} organization import
      register: org_result

    - name: 恢复项目配置
      shell: |
        cat {{ temp_dir }}/{{ backup_date.stdout }}/projects.json | {{ awx_cli }} project import
      register: proj_result

    - name: 恢复模板配置
      shell: |
        cat {{ temp_dir }}/{{ backup_date.stdout }}/templates.json | {{ awx_cli }} job_template import
      register: temp_result

    - name: 恢复清单配置
      shell: |
        cat {{ temp_dir }}/{{ backup_date.stdout }}/inventories.json | {{ awx_cli }} inventory import
      register: inv_result

    - name: 恢复凭据配置
      shell: |
        cat {{ temp_dir }}/{{ backup_date.stdout }}/credentials.json | {{ awx_cli }} credential import
      register: cred_result

    - name: 清理临时文件
      file:
        path: "{{ temp_dir }}"
        state: absent 