---
- name: 检查 K3s 状态
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查 K3s 进程和文件
      shell: |
        echo "=== K3s 进程状态 ==="
        ps aux | grep k3s | grep -v grep || true
        
        echo "=== K3s 二进制文件 ==="
        which k3s || true
        
        echo "=== K3s 配置目录 ==="
        ls -la /etc/rancher/k3s/ || true
        
        echo "=== K3s 数据目录 ==="
        ls -la /var/lib/rancher/k3s/ || true
        
        echo "=== 系统资源使用情况 ==="
        df -h || true
        
        echo "=== 网络端口 ==="
        cat /proc/net/tcp || true
      register: k3s_status
      changed_when: false
      ignore_errors: yes

    - name: 显示 K3s 状态
      debug:
        msg: "{{ k3s_status.stdout_lines }}"

    - name: 检查 K3s 文件
      shell: |
        echo "=== K3s 文件检查 ==="
        ls -l /usr/local/bin/k3s || true
        ls -l /etc/rancher/k3s/k3s.yaml || true
        ls -l /var/lib/rancher/k3s || true
      register: k3s_files
      changed_when: false
      ignore_errors: yes

    - name: 显示 K3s 文件状态
      debug:
        msg: "{{ k3s_files.stdout_lines }}"

    - name: 检查网络端口
      shell: |
        echo "=== 监听端口 ==="
        netstat -nltp || ss -nltp || true
      register: port_status
      changed_when: false
      ignore_errors: yes

    - name: 显示端口状态
      debug:
        msg: "{{ port_status.stdout_lines }}" 