---
- name: 检查 K3s 状态
  hosts: all
  tasks:
    - name: 检查 K3s 服务状态
      shell: |
        echo "=== K3s 服务状态 ==="
        systemctl status k3s || true
        
        echo "=== K3s 版本信息 ==="
        k3s --version || true
        
        echo "=== K3s 节点状态 ==="
        k3s kubectl get nodes || true
        
        echo "=== K3s Pod 状态 ==="
        k3s kubectl get pods -A || true
        
        echo "=== 系统资源使用情况 ==="
        free -h
        df -h /
      register: k3s_status
      changed_when: false
      ignore_errors: yes

    - name: 显示 K3s 状态
      debug:
        msg: "{{ k3s_status.stdout_lines }}"

    - name: 检查 K3s 文件
      stat:
        path: "{{ item }}"
      loop:
        - /usr/local/bin/k3s
        - /etc/rancher/k3s/k3s.yaml
        - /var/lib/rancher/k3s
      register: k3s_files
      ignore_errors: yes

    - name: 显示 K3s 文件状态
      debug:
        msg: |
          K3s 文件检查结果：
          {% for item in k3s_files.results %}
          - {{ item.item }}: {{ '存在' if item.stat.exists|default(false) else '不存在' }}
          {% endfor %}

    - name: 检查网络端口
      shell: |
        echo "=== 监听端口 ==="
        netstat -nltp 2>/dev/null || ss -nltp 2>/dev/null || true
      register: port_status
      changed_when: false
      ignore_errors: yes

    - name: 显示端口状态
      debug:
        msg: "{{ port_status.stdout_lines }}" 