---
- name: 检查服务状态
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查所有服务状态
      shell: |
        echo "=== 服务运行状态 ==="
        /usr/local/bin/k3s kubectl get pods --all-namespaces -o wide
        
        echo -e "\n=== 资源使用情况 ==="
        /usr/local/bin/k3s kubectl top pods --all-namespaces
        
        echo -e "\n=== 节点资源使用情况 ==="
        /usr/local/bin/k3s kubectl top nodes
        
        echo -e "\n=== 服务健康状态 ==="
        /usr/local/bin/k3s kubectl get events --all-namespaces --sort-by='.lastTimestamp' | tail -n 20
        
        echo -e "\n=== 检查特定服务 ==="
        namespaces=("magento-1" "magento-2" "magento-shared")
        for ns in "${namespaces[@]}"; do
          echo -e "\n命名空间: $ns"
          echo "Pod 状态:"
          /usr/local/bin/k3s kubectl get pods -n $ns
          echo "服务状态:"
          /usr/local/bin/k3s kubectl get svc -n $ns
        done
      register: status_result

    - name: 显示状态结果
      debug:
        msg: "{{ status_result.stdout_lines }}" 