---
- name: 检查 Percona 版本
  hosts: all
  gather_facts: no
  tasks:
    - name: 获取版本信息
      shell: |
        echo "=== Percona Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods -l app=percona
        
        echo -e "\n=== Percona 版本信息 ==="
        POD_NAME=$(/usr/local/bin/k3s kubectl get pods -l app=percona -o jsonpath='{.items[0].metadata.name}')
        echo "MySQL 命令版本:"
        /usr/local/bin/k3s kubectl exec $POD_NAME -- mysql -V
        
        echo -e "\nMySQL 服务器版本:"
        /usr/local/bin/k3s kubectl exec $POD_NAME -- mysql -uroot -proot123 -e "SELECT VERSION();"
        
        echo -e "\n=== 详细版本信息 ==="
        /usr/local/bin/k3s kubectl exec $POD_NAME -- mysql -uroot -proot123 -e "SHOW VARIABLES LIKE '%version%';"
      register: version_info

    - name: 显示版本信息
      debug:
        msg: "{{ version_info.stdout_lines | default([]) }}" 