---
- name: 检查 K3s 状态
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查 K3s 服务状态
      shell: |
        echo "=== K3s 服务状态 ==="
        systemctl status k3s || true
        
        echo "=== K3s 版本信息 ==="
        k3s --version || true
        
        echo "=== K3s 节点状态 ==="
        k3s kubectl get nodes || true
        
        echo "=== K3s Pod 状态 ==="
        k3s kubectl get pods -A || true
        
        echo "=== 系统资源使用情况 ==="
        free -h || true
        df -h / || true
      register: k3s_status
      changed_when: false
      ignore_errors: yes

    - name: 显示 K3s 状态
      debug:
        msg: "{{ k3s_status.stdout_lines }}"

    - name: 检查 K3s 文件
      shell: |
        echo "=== K3s 文件检查 ==="
        ls -l /usr/local/bin/k3s || true
        ls -l /etc/rancher/k3s/k3s.yaml || true
        ls -l /var/lib/rancher/k3s || true
      register: k3s_files
      changed_when: false
      ignore_errors: yes

    - name: 显示 K3s 文件状态
      debug:
        msg: "{{ k3s_files.stdout_lines }}"

    - name: 检查网络端口
      shell: |
        echo "=== 监听端口 ==="
        netstat -nltp || ss -nltp || true
      register: port_status
      changed_when: false
      ignore_errors: yes

    - name: 显示端口状态
      debug:
        msg: "{{ port_status.stdout_lines }}" 