---
- name: 检查端口和服务状态
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查系统状态
      shell: |
        echo "=== 检查所有命名空间中使用 NodePort 30306 的服务 ==="
        /usr/local/bin/k3s kubectl get svc --all-namespaces -o wide | grep "30306" || echo "没有找到使用 30306 端口的服务"
        
        echo -e "\n=== 检查所有命名空间中的 Percona 服务 ==="
        /usr/local/bin/k3s kubectl get svc --all-namespaces -o wide | grep -i "percona" || echo "没有找到 Percona 服务"
        
        echo -e "\n=== 检查所有命名空间中的 Percona Pods ==="
        /usr/local/bin/k3s kubectl get pods --all-namespaces -o wide | grep -i "percona" || echo "没有找到 Percona Pods"
        
        echo -e "\n=== 检查所有服务的 NodePort ==="
        /usr/local/bin/k3s kubectl get svc --all-namespaces -o wide | grep "NodePort"
      register: check_result

    - name: 显示检查结果
      debug:
        msg: "{{ check_result.stdout_lines | default([]) }}" 