---
- name: 使用 Galaxy 角色
  hosts: all
  vars:
    role_name: "{{ role | default('') }}"
    namespace: "{{ namespace | default('default') }}"
  
  pre_tasks:
    - name: 验证必要参数
      fail:
        msg: "必须指定 role 参数"
      when: role_name == ''

  roles:
    - "{{ role_name }}"

  post_tasks:
    - name: 显示安装完成
      debug:
        msg: "角色 {{ role_name }} 已安装完成" 