---
- name: 安装 Magento 环境
  hosts: all
  vars:
    component: "{{ component | default('') }}"  # 要安装的组件名称
    namespace: "{{ namespace | default('magento-shared') }}"
    
  pre_tasks:
    - name: 加载环境配置
      include_vars:
        file: magento-env.yml
        
    - name: 验证组件名称
      fail:
        msg: "必须指定 component 参数，可选值: {{ environments | map(attribute='name') | list | join(', ') }}"
      when: component == ''
      
    - name: 查找组件配置
      set_fact:
        selected_component: "{{ environments | selectattr('name', 'equalto', component) | list | first }}"
      when: component != ''
      
  roles:
    - role: "{{ selected_component.role }}"
      vars:
        # 通用版本变量
        nginx_version: "{{ selected_component.version | default('latest') if selected_component.name == 'nginx' }}"
        php_version: "{{ selected_component.version | default('latest') if selected_component.name.startswith('php') }}"
        mysql_version: "{{ selected_component.version | default('latest') if selected_component.name == 'percona' }}"
        redis_version: "{{ selected_component.version | default('latest') if selected_component.name == 'redis' }}"
        rabbitmq_version: "{{ selected_component.version | default('latest') if selected_component.name == 'rabbitmq' }}"
        varnish_version: "{{ selected_component.version | default('latest') if selected_component.name == 'varnish' }}"
        elasticsearch_version: "{{ selected_component.version | default('latest') if selected_component.name == 'opensearch' }}"
        composer_version: "{{ selected_component.version | default('latest') if selected_component.name == 'composer' }}"
        
  post_tasks:
    - name: 显示安装完成
      debug:
        msg: "组件 {{ component }}({{ selected_component.role }}) 安装完成，版本: {{ selected_component.version | default('latest') }}" 