---
- name: 安装 Nginx 1.24
  hosts: all
  gather_facts: no
  tasks:
    - name: 设置变量
      set_fact:
        use_namespace: "{{ namespace | default('default') }}"
        use_nodeport: "{{ nodeport | default('30180') }}"

    - name: 创建 Nginx 配置
      copy:
        dest: /tmp/nginx.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: {{ use_namespace }}
            labels:
              app: nginx
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.24
                  ports:
                  - containerPort: 80
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "100m"
                    limits:
                      memory: "256Mi"
                      cpu: "200m"
                  readinessProbe:
                    httpGet:
                      path: /
                      port: 80
                    initialDelaySeconds: 5
                    periodSeconds: 5
                  volumeMounts:
                  - name: nginx-conf
                    mountPath: /etc/nginx/conf.d
                volumes:
                - name: nginx-conf
                  emptyDir: {}
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: {{ use_namespace }}
            labels:
              app: nginx
          spec:
            type: NodePort
            ports:
            - port: 80
              targetPort: 80
              nodePort: {{ use_nodeport }}
            selector:
              app: nginx

    - name: 清理旧的部署
      shell: |
        /usr/local/bin/k3s kubectl delete -f /tmp/nginx.yaml || true
        sleep 5
      register: cleanup_result

    - name: 部署 Nginx
      shell: |
        /usr/local/bin/k3s kubectl apply -f /tmp/nginx.yaml
        
        echo "等待 Nginx Pod 就绪..."
        for i in {1..30}; do
          if /usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=nginx -o jsonpath='{.items[0].status.phase}' | grep -q "Running"; then
            echo "Nginx Pod 已就绪"
            break
          fi
          echo "等待中... $i"
          sleep 5
        done
        
        echo -e "\n=== Nginx 部署状态 ==="
        echo "Pod 状态:"
        /usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=nginx
        echo -e "\nService 状态:"
        /usr/local/bin/k3s kubectl get svc -n {{ use_namespace }} -l app=nginx
        
        echo -e "\n=== 访问地址 ==="
        NODE_IP=$(/usr/local/bin/k3s kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')
        echo "http://$NODE_IP:{{ use_nodeport }}"
      register: deploy_result

    - name: 显示部署结果
      debug:
        msg: "{{ deploy_result.stdout_lines }}" 