---
- name: 安装 PHP 8.3 及扩展
  hosts: all
  gather_facts: no
  tasks:
    - name: 创建 PHP-FPM 配置
      copy:
        dest: /tmp/php-fpm.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: php-fpm
            labels:
              app: php-fpm
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: php-fpm
            template:
              metadata:
                labels:
                  app: php-fpm
              spec:
                containers:
                - name: php-fpm
                  image: php:8.3-fpm
                  ports:
                  - containerPort: 9000
                    name: fpm
                  resources:
                    limits:
                      cpu: "1"
                      memory: "1Gi"
                    requests:
                      cpu: "0.5"
                      memory: "512Mi"
                  lifecycle:
                    postStart:
                      exec:
                        command:
                        - /bin/sh
                        - -c
                        - |
                          # 安装基础依赖
                          apt-get update && apt-get install -y \
                            libzip-dev \
                            libxml2-dev \
                            libxslt1-dev \
                            libgd-dev \
                            libicu-dev \
                            libsodium-dev \
                            libcurl4-openssl-dev \
                            && rm -rf /var/lib/apt/lists/*
                          
                          # 安装 PHP 扩展
                          docker-php-ext-install -j$(nproc) \
                            bcmath \
                            ctype \
                            curl \
                            dom \
                            fileinfo \
                            filter \
                            gd \
                            hash \
                            iconv \
                            intl \
                            json \
                            mbstring \
                            opcache \
                            pdo_mysql \
                            simplexml \
                            soap \
                            sockets \
                            sodium \
                            tokenizer \
                            xml \
                            xmlwriter \
                            xsl \
                            zip

                          # 配置 opcache
                          echo "opcache.enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
                          echo "opcache.enable_cli=1" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
                          echo "opcache.memory_consumption=128" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
                          echo "opcache.interned_strings_buffer=8" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
                          echo "opcache.max_accelerated_files=4000" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
                          echo "opcache.revalidate_freq=60" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
                          echo "opcache.fast_shutdown=1" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: php-fpm
          spec:
            ports:
            - port: 9000
              targetPort: 9000
              name: fpm
            selector:
              app: php-fpm

    - name: 清理旧部署
      shell: |
        /usr/local/bin/k3s kubectl delete -f /tmp/php-fpm.yaml || true
        sleep 5

    - name: 部署 PHP-FPM
      shell: /usr/local/bin/k3s kubectl apply -f /tmp/php-fpm.yaml
      register: deploy_result

    - name: 等待 Pod 就绪
      shell: |
        echo "等待 Pod 就绪..."
        /usr/local/bin/k3s kubectl wait --for=condition=ready pod -l app=php-fpm --timeout=300s
      register: wait_result

    - name: 显示 PHP 信息
      shell: |
        echo "=== PHP-FPM 部署状态 ==="
        /usr/local/bin/k3s kubectl get pods -l app=php-fpm
        
        echo -e "\n=== PHP 版本信息 ==="
        POD_NAME=$(/usr/local/bin/k3s kubectl get pods -l app=php-fpm -o jsonpath='{.items[0].metadata.name}')
        /usr/local/bin/k3s kubectl exec $POD_NAME -- php -v
        
        echo -e "\n=== PHP 扩展列表 ==="
        /usr/local/bin/k3s kubectl exec $POD_NAME -- php -m
        
        echo -e "\n=== Opcache 配置 ==="
        /usr/local/bin/k3s kubectl exec $POD_NAME -- php -i | grep -i opcache
      register: php_info

    - name: 显示 PHP 信息
      debug:
        msg: "{{ php_info.stdout_lines | default([]) }}" 