---
- name: 安装 Percona Server 8.0
  hosts: all
  gather_facts: no
  tasks:
    - name: 创建 Percona 配置
      copy:
        dest: /tmp/percona.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: percona
            namespace: "{{ namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: percona
            template:
              metadata:
                labels:
                  app: percona
              spec:
                containers:
                - name: percona
                  image: percona:8.0
                  ports:
                  - containerPort: 3306
                  env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: "magento"
                  resources:
                    limits:
                      cpu: "2"
                      memory: "4Gi"
                    requests:
                      cpu: "1"
                      memory: "2Gi"
                  volumeMounts:
                  - name: mysql-data
                    mountPath: /var/lib/mysql
                volumes:
                - name: mysql-data
                  hostPath:
                    path: /data/percona
                    type: DirectoryOrCreate
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: percona
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: percona
            ports:
            - port: 3306
              targetPort: 3306
              nodePort: 30306
            type: NodePort

    - name: 清理旧部署
      shell: |
        /usr/local/bin/k3s kubectl delete -f /tmp/percona.yaml || true
        sleep 5
      register: cleanup_result

    - name: 部署 Percona
      shell: |
        /usr/local/bin/k3s kubectl apply -f /tmp/percona.yaml
      register: deploy_result

    - name: 等待 Percona Pod 就绪
      shell: |
        for i in {1..30}; do
          if /usr/local/bin/k3s kubectl get pods -n {{ namespace }} -l app=percona -o jsonpath='{.items[0].status.phase}' | grep -q "Running"; then
            echo "Percona Pod 已就绪"
            break
          fi
          echo "等待 Percona Pod 就绪... $i"
          sleep 3
        done
      register: wait_result

    - name: 显示 Percona 状态
      shell: |
        echo "=== Percona Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods -n {{ namespace }} -l app=percona
        
        echo -e "\n=== Percona 服务状态 ==="
        /usr/local/bin/k3s kubectl get svc -n {{ namespace }} -l app=percona
      register: status_result

    - name: 显示部署结果
      debug:
        msg: 
          - "{{ deploy_result.stdout_lines | default([]) }}"
          - "{{ wait_result.stdout_lines | default([]) }}"
          - "{{ status_result.stdout_lines | default([]) }}" 