---
- name: 安装和配置 K3s
  hosts: all
  gather_facts: yes
  tasks:
    - name: 检查 K3s 是否已安装
      stat:
        path: /usr/local/bin/k3s
      register: k3s_binary

    - name: 下载 K3s 安装脚本
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'
      when: not k3s_binary.stat.exists

    - name: 安装 K3s
      shell: |
        export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644"
        sh /tmp/k3s-install.sh
      when: not k3s_binary.stat.exists

    - name: 等待 K3s 服务启动
      systemd:
        name: k3s
        state: started
        enabled: yes
      register: k3s_service

    - name: 等待 K3s API 就绪
      wait_for:
        port: 6443
        timeout: 300
      register: api_wait

    - name: 检查 K3s 状态
      shell: |
        echo "=== K3s 版本 ==="
        /usr/local/bin/k3s --version
        
        echo -e "\n=== K3s 服务状态 ==="
        systemctl status k3s
        
        echo -e "\n=== 节点状态 ==="
        /usr/local/bin/k3s kubectl get nodes
        
        echo -e "\n=== 系统 Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods -A
      register: k3s_status
      ignore_errors: yes

    - name: 显示 K3s 状态
      debug:
        msg: "{{ k3s_status.stdout_lines | default([]) }}" 