---
- name: 安装 Magento 环境
  hosts: all
  vars:
    component: "{{ component | default('') }}"  # 要安装的组件名称
    group: "{{ group | default('') }}"  # 要安装的组名称
    namespace: "{{ namespace | default('magento-shared') }}"
    
  pre_tasks:
    - name: 加载环境配置
      include_vars:
        file: magento-env.yml
        
    - name: 验证参数
      fail:
        msg: "必须指定 component 或 group 参数。可选组: {{ install_groups | map(attribute='name') | list | join(', ') }}，可选组件: {{ environments | map(attribute='name') | list | join(', ') }}"
      when: component == '' and group == ''
      
    - name: 查找组配置
      set_fact:
        selected_group: "{{ install_groups | selectattr('name', 'equalto', group) | list | first }}"
      when: group != ''
      
    - name: 查找组件配置
      set_fact:
        selected_component: "{{ environments | selectattr('name', 'equalto', component) | list | first }}"
      when: component != ''
      
    - name: 显示安装计划
      debug:
        msg: "{{ '准备安装组: ' + selected_group.title if group != '' else '准备安装组件: ' + component }}"
        
  tasks:
    - name: 安装组内所有组件
      include_tasks: install-component.yml
      vars:
        component_name: "{{ item }}"
      loop: "{{ selected_group.components }}"
      when: group != ''
      
    - name: 安装单个组件
      include_tasks: install-component.yml
      vars:
        component_name: "{{ component }}"
      when: component != ''
      
  post_tasks:
    - name: 显示安装完成
      debug:
        msg: "{{ '组 ' + selected_group.title if group != '' else '组件 ' + component }} 安装完成" 