---
- name: 安装 Nginx
  hosts: all
  gather_facts: no
  tasks:
    - name: 创建命名空间
      shell: |
        /usr/local/bin/k3s kubectl create namespace magento || true
      register: namespace_result

    - name: 创建 Nginx 配置
      copy:
        dest: /tmp/nginx.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: magento
            labels:
              app: nginx
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.24
                  ports:
                  - containerPort: 80
                    name: http
                  resources:
                    limits:
                      cpu: "1"
                      memory: "1Gi"
                    requests:
                      cpu: "0.5"
                      memory: "512Mi"
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: magento
          spec:
            type: NodePort
            ports:
            - port: 80
              targetPort: 80
              nodePort: 30080
              name: http
            selector:
              app: nginx

    - name: 清理旧部署
      shell: |
        /usr/local/bin/k3s kubectl delete -f /tmp/nginx.yaml || true
        sleep 5

    - name: 部署 Nginx
      shell: /usr/local/bin/k3s kubectl apply -f /tmp/nginx.yaml
      register: deploy_result

    - name: 等待 Pod 就绪
      shell: |
        echo "等待 Pod 就绪..."
        /usr/local/bin/k3s kubectl wait --for=condition=ready pod -l app=nginx -n magento --timeout=300s
      register: wait_result

    - name: 显示 Nginx 访问信息
      shell: |
        echo "=== Nginx 部署状态 ==="
        /usr/local/bin/k3s kubectl get pods -l app=nginx -n magento
        
        echo -e "\n=== Nginx 服务信息 ==="
        /usr/local/bin/k3s kubectl get svc nginx -n magento
        
        echo -e "\n=== Nginx 版本信息 ==="
        POD_NAME=$(/usr/local/bin/k3s kubectl get pods -l app=nginx -n magento -o jsonpath='{.items[0].metadata.name}')
        /usr/local/bin/k3s kubectl exec $POD_NAME -n magento -- nginx -v
      register: access_info

    - name: 显示访问信息
      debug:
        msg: "{{ access_info.stdout_lines | default([]) }}" 