---
- name: 安装 RabbitMQ 3.13
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('default') }}"
    use_nodeport: "{{ nodeport | default('30672') }}"

  tasks:
    - name: 创建命名空间
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ use_namespace }}"
      when: use_namespace != "default"
      register: namespace_result

    - name: 创建 RabbitMQ 配置
      copy:
        dest: /tmp/rabbitmq.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: rabbitmq
            namespace: {{ use_namespace }}
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: rabbitmq
            template:
              metadata:
                labels:
                  app: rabbitmq
              spec:
                containers:
                - name: rabbitmq
                  image: rabbitmq:3.13-management
                  ports:
                  - containerPort: 5672
                    name: amqp
                  - containerPort: 15672
                    name: management
                  readinessProbe:
                    tcpSocket:
                      port: 5672
                    initialDelaySeconds: 10
                    periodSeconds: 10
                  livenessProbe:
                    tcpSocket:
                      port: 5672
                    initialDelaySeconds: 60
                    periodSeconds: 20
                    timeoutSeconds: 5
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: rabbitmq
            namespace: {{ use_namespace }}
          spec:
            type: NodePort
            ports:
            - port: 5672
              targetPort: 5672
              nodePort: {{ use_nodeport }}
              name: amqp
            - port: 15672
              targetPort: 15672
              nodePort: {{ use_nodeport | int + 1 }}
              name: management
            selector:
              app: rabbitmq

    - name: 清理旧的部署
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('file', '/tmp/rabbitmq.yaml') | from_yaml_all | list }}"
      register: cleanup_result

    - name: 等待资源清理
      pause:
        seconds: 5

    - name: 部署 RabbitMQ
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/tmp/rabbitmq.yaml') | from_yaml_all | list }}"
      register: deploy_result

    - name: 等待 Pod 就绪
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ use_namespace }}"
        label_selectors:
          - app=rabbitmq
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Ready
          status: "True"
      register: pod_result

    - name: 获取节点 IP
      shell: "/usr/local/bin/k3s kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}'"
      register: node_ip
      changed_when: false

    - name: 显示访问信息
      debug:
        msg:
          - "=== 访问信息 ==="
          - "AMQP 端口: {{ node_ip.stdout }}:{{ use_nodeport }}"
          - "管理界面: http://{{ node_ip.stdout }}:{{ use_nodeport | int + 1 }}"
          - "默认用户名/密码: guest/guest" 