---
- name: 在 K3s 中部署 Nginx
  hosts: all
  gather_facts: no
  tasks:
    - name: 创建 Nginx 配置
      copy:
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: default
          spec:
            selector:
              matchLabels:
                app: nginx
            replicas: 1
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.24
                  ports:
                  - containerPort: 80
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "100m"
                    limits:
                      memory: "128Mi"
                      cpu: "200m"
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: default
          spec:
            type: NodePort
            ports:
            - port: 80
              targetPort: 80
              nodePort: 30080
            selector:
              app: nginx
        dest: /tmp/nginx.yaml

    - name: 部署 Nginx
      shell: /usr/local/bin/k3s kubectl apply -f /tmp/nginx.yaml
      register: deploy_result

    - name: 显示部署结果
      debug:
        msg: "{{ deploy_result.stdout_lines | default([]) }}"

    - name: 等待 Nginx Pod 就绪
      shell: |
        for i in {1..30}; do
          if /usr/local/bin/k3s kubectl get pods -l app=nginx | grep Running; then
            echo "Nginx Pod 已就绪"
            exit 0
          fi
          echo "等待 Nginx Pod 就绪... $i"
          sleep 2
        done
      register: wait_result

    - name: 获取 Nginx 访问信息
      shell: |
        echo "=== Nginx Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods -l app=nginx
        
        echo -e "\n=== Nginx Service 状态 ==="
        /usr/local/bin/k3s kubectl get svc nginx
        
        echo -e "\n=== Nginx 访问地址 ==="
        NODE_IP=$(/usr/local/bin/k3s kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')
        echo "http://$NODE_IP:30080"
      register: nginx_info

    - name: 显示 Nginx 信息
      debug:
        msg: "{{ nginx_info.stdout_lines | default([]) }}" 