---
- name: 在 K3s 中安装 Nginx 1.24
  hosts: all
  gather_facts: no
  tasks:
    - name: 创建 Nginx 部署配置
      copy:
        content: |
          ---
          # Nginx Deployment
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.24
                  ports:
                  - containerPort: 80
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "100m"
                    limits:
                      memory: "128Mi"
                      cpu: "200m"
          ---
          # Nginx Service
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: default
          spec:
            selector:
              app: nginx
            ports:
            - port: 80
              targetPort: 80
            type: ClusterIP
          ---
          # Nginx Ingress
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: nginx-ingress
            namespace: default
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
          spec:
            rules:
            - http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: nginx-service
                      port:
                        number: 80
        dest: /tmp/nginx-deployment.yml

    - name: 部署 Nginx
      shell: |
        /usr/local/bin/k3s kubectl apply -f /tmp/nginx-deployment.yml
      register: deploy_result

    - name: 等待 Nginx Pod 就绪
      shell: |
        for i in {1..30}; do
          if /usr/local/bin/k3s kubectl get pods | grep nginx-deployment | grep Running; then
            echo "Nginx Pod 已就绪"
            exit 0
          fi
          echo "等待 Nginx Pod 就绪... $i"
          sleep 2
        done
        echo "Nginx Pod 启动超时"
        exit 1
      register: nginx_wait
      ignore_errors: yes

    - name: 获取 Nginx 访问信息
      shell: |
        echo "=== Nginx Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods | grep nginx
        
        echo -e "\n=== Nginx Service 状态 ==="
        /usr/local/bin/k3s kubectl get svc nginx-service
        
        echo -e "\n=== Nginx Ingress 状态 ==="
        /usr/local/bin/k3s kubectl get ingress nginx-ingress
        
        echo -e "\n=== Nginx 访问地址 ==="
        echo "http://$(/usr/local/bin/k3s kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')"
      register: nginx_status
      ignore_errors: yes

    - name: 显示 Nginx 状态
      debug:
        msg: "{{ nginx_status.stdout_lines | default([]) }}"