---
- name: 安装和使用 Galaxy 角色
  hosts: all
  vars:
    role_name: "{{ role | default('') }}"
    namespace: "{{ namespace | default('default') }}"
  
  pre_tasks:
    - name: 验证必要参数
      fail:
        msg: "必须指定 role 参数"
      when: role_name == ''

  tasks:
    - name: 下载角色
      command: "ansible-galaxy role install {{ role_name }}"
      register: install_result

    - name: 显示安装结果
      debug:
        var: install_result

  roles:
    - "{{ role_name }}" 