---
- name: 安装 Nginx 1.24
  hosts: all
  gather_facts: no
  tasks:
    - name: 创建 Nginx 配置
      copy:
        dest: /tmp/nginx.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: "{{ namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.24
                  resources:
                    limits:
                      cpu: "1"
                      memory: "1Gi"
                    requests:
                      cpu: "500m"
                      memory: "512Mi"
                  readinessProbe:
                    httpGet:
                      path: /
                      port: 80
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  ports:
                  - containerPort: 80
                  volumeMounts:
                  - name: nginx-conf
                    mountPath: /etc/nginx/conf.d
                volumes:
                - name: nginx-conf
                  emptyDir: {}
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: nginx
            ports:
            - port: 80
              targetPort: 80
              nodePort: 30080
            type: NodePort

    - name: 清理旧的部署
      shell: |
        /usr/local/bin/k3s kubectl delete -f /tmp/nginx.yaml || true
        sleep 5
      register: cleanup_result

    - name: 部署 Nginx
      shell: |
        /usr/local/bin/k3s kubectl apply -f /tmp/nginx.yaml
      register: deploy_result

    - name: 等待 Nginx Pod 就绪
      shell: |
        for i in {1..30}; do
          if /usr/local/bin/k3s kubectl get pods -n {{ namespace }} -l app=nginx -o jsonpath='{.items[0].status.phase}' | grep -q "Running"; then
            echo "Nginx Pod 已就绪"
            break
          fi
          echo "等待 Nginx Pod 就绪... $i"
          sleep 3
        done
      register: wait_result

    - name: 显示 Nginx 状态
      shell: |
        echo "=== Nginx Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods -n {{ namespace }} -l app=nginx
        
        echo -e "\n=== Nginx 服务状态 ==="
        /usr/local/bin/k3s kubectl get svc -n {{ namespace }} -l app=nginx
        
        echo -e "\n=== Nginx 访问地址 ==="
        NODE_IP=$(/usr/local/bin/k3s kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')
        echo "http://$NODE_IP:30080"
      register: status_result

    - name: 显示部署结果
      debug:
        msg: 
          - "{{ deploy_result.stdout_lines | default([]) }}"
          - "{{ wait_result.stdout_lines | default([]) }}"
          - "{{ status_result.stdout_lines | default([]) }}" 