---
- name: 安装 PHP-FPM 8.3
  hosts: all
  gather_facts: yes
  
  pre_tasks:
    - name: 安装 PHP 角色
      command: ansible-galaxy install geerlingguy.php
      
  tasks:
    - name: 安装 PHP 8.3
      include_role:
        name: geerlingguy.php
      vars:
        php_version: "8.3"
        php_packages:
          - php8.3-cli
          - php8.3-common
          - php8.3-fpm
          - php8.3-bcmath
          - php8.3-curl
          - php8.3-dev
          - php8.3-gd
          - php8.3-iconv
          - php8.3-intl
          - php8.3-mbstring
          - php8.3-mysql
          - php8.3-opcache
          - php8.3-soap
          - php8.3-xml
          - php8.3-xsl
          - php8.3-zip
        php_enable_webserver: false
        php_enable_php_fpm: true
        php_fpm_listen: "0.0.0.0:9000"
        php_fpm_pm_max_children: 50
        php_fpm_pm_start_servers: 5
        php_fpm_pm_min_spare_servers: 5
        php_fpm_pm_max_spare_servers: 35
        
        # PHP 配置
        php_memory_limit: "1G"
        php_max_execution_time: 1800
        php_max_input_time: 1800
        php_max_input_vars: 50000
        php_realpath_cache_size: "10M"
        php_upload_max_filesize: "100M"
        php_post_max_size: "100M"
        
        # OPcache 配置
        php_opcache_enable: 1
        php_opcache_memory_consumption: 128
        php_opcache_interned_strings_buffer: 8
        php_opcache_max_accelerated_files: 4000
        php_opcache_revalidate_freq: 60
        php_opcache_fast_shutdown: 1
        
    - name: 显示 PHP 版本
      command: php -v
      register: php_version_output
      
    - name: 显示 PHP-FPM 状态
      command: systemctl status php8.3-fpm
      register: php_fpm_status
      
    - name: 显示安装结果
      debug:
        msg:
          - "PHP 版本信息:"
          - "{{ php_version_output.stdout_lines }}"
          - ""
          - "PHP-FPM 状态:"
          - "{{ php_fpm_status.stdout_lines }}" 