---
- name: 安装 RabbitMQ 3.13
  hosts: all
  gather_facts: no
  tasks:
    - name: 创建 RabbitMQ 配置
      copy:
        dest: /tmp/rabbitmq.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: rabbitmq
            namespace: "{{ namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: rabbitmq
            template:
              metadata:
                labels:
                  app: rabbitmq
              spec:
                containers:
                - name: rabbitmq
                  image: rabbitmq:3.13-management
                  resources:
                    limits:
                      cpu: "1"
                      memory: "1Gi"
                    requests:
                      cpu: "500m"
                      memory: "512Mi"
                  ports:
                  - containerPort: 5672
                    name: amqp
                  - containerPort: 15672
                    name: management
                  readinessProbe:
                    tcpSocket:
                      port: 5672
                    initialDelaySeconds: 10
                    periodSeconds: 30
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: rabbitmq
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: rabbitmq
            ports:
            - port: 5672
              targetPort: 5672
              nodePort: 30672
              name: amqp
            - port: 15672
              targetPort: 15672
              nodePort: 31672
              name: management
            type: NodePort

    - name: 清理旧的部署
      shell: |
        /usr/local/bin/k3s kubectl delete -f /tmp/rabbitmq.yaml || true
        sleep 5
      register: cleanup_result

    - name: 部署 RabbitMQ
      shell: |
        /usr/local/bin/k3s kubectl apply -f /tmp/rabbitmq.yaml
      register: deploy_result

    - name: 等待 RabbitMQ Pod 就绪
      shell: |
        for i in {1..30}; do
          if /usr/local/bin/k3s kubectl get pods -n {{ namespace }} -l app=rabbitmq -o jsonpath='{.items[0].status.phase}' | grep -q "Running"; then
            echo "RabbitMQ Pod 已就绪"
            break
          fi
          echo "等待 RabbitMQ Pod 就绪... $i"
          sleep 3
        done
      register: wait_result

    - name: 显示 RabbitMQ 状态
      shell: |
        echo "=== RabbitMQ Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods -n {{ namespace }} -l app=rabbitmq
        
        echo -e "\n=== RabbitMQ 服务状态 ==="
        /usr/local/bin/k3s kubectl get svc -n {{ namespace }} -l app=rabbitmq
        
        echo -e "\n=== RabbitMQ 访问地址 ==="
        NODE_IP=$(/usr/local/bin/k3s kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')
        echo "AMQP: amqp://$NODE_IP:30672"
        echo "管理界面: http://$NODE_IP:31672"
        echo "默认用户名/密码: guest/guest"
      register: status_result

    - name: 显示部署结果
      debug:
        msg: 
          - "{{ deploy_result.stdout_lines | default([]) }}"
          - "{{ wait_result.stdout_lines | default([]) }}"
          - "{{ status_result.stdout_lines | default([]) }}" 