---
- name: 通用角色安装
  hosts: all
  vars:
    role_name: "{{ role | default('') }}"  # 在 AWX 中设置
    namespace: "{{ namespace | default('default') }}"
  
  pre_tasks:
    - name: 验证必要参数
      fail:
        msg: "必须指定 role 参数"
      when: role_name == ''
      
    - name: 确保 ansible-galaxy 可用
      shell: |
        if ! command -v ansible-galaxy &> /dev/null; then
          apt-get update
          apt-get install -y ansible
        fi
      become: yes
      
    - name: 安装所需角色
      shell: |
        ansible-galaxy install {{ role_name }}
      register: install_result
      
    - name: 显示安装结果
      debug:
        var: install_result
  
  roles:
    - "{{ role_name }}"
  
  post_tasks:
    - name: 显示安装结果
      debug:
        msg: "角色 {{ role_name }} 安装完成" 