---
collections:
  - kubernetes.core
  - community.kubernetes
roles:
  - name: geerlingguy.nginx
    version: "3.1.3"
  - name: geerlingguy.mysql
    version: "3.3.2"
  - name: geerlingguy.php
    version: "4.9.0" 