---
- name: 重启 AWX
  hosts: all
  gather_facts: no
  tasks:
    - name: 重启 AWX Pod
      shell: |
        echo "=== 重启 AWX Pod ==="
        # 获取 AWX Pod 名称
        AWX_POD=$(/usr/local/bin/k3s kubectl get pods -n awx -l app.kubernetes.io/component=web --no-headers -o custom-columns=":metadata.name")
        
        if [ -n "$AWX_POD" ]; then
          echo "删除 AWX Pod: $AWX_POD"
          /usr/local/bin/k3s kubectl delete pod -n awx $AWX_POD
          
          echo "等待新的 Pod 启动..."
          for i in $(seq 1 30); do
            if /usr/local/bin/k3s kubectl get pods -n awx -l app.kubernetes.io/component=web | grep -q Running; then
              echo "AWX Pod 已重启并运行"
              break
            fi
            echo "等待 Pod 就绪... $i/30"
            sleep 10
          done
        else
          echo "未找到 AWX Pod"
        fi
        
        echo -e "\n=== AWX Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods -n awx
      register: restart_result

    - name: 显示重启结果
      debug:
        msg: "{{ restart_result.stdout_lines | default([]) }}" 