---
- name: 重启 K3s
  hosts: all
  gather_facts: no
  tasks:
    - name: 重启 K3s 服务
      shell: |
        echo "=== 重启 K3s 服务 ==="
        systemctl restart k3s
        
        echo "等待 K3s 就绪..."
        for i in $(seq 1 30); do
          if systemctl is-active k3s >/dev/null 2>&1; then
            echo "K3s 服务已启动"
            break
          fi
          echo "等待 K3s 启动... $i/30"
          sleep 2
        done
        
        echo "等待节点就绪..."
        for i in $(seq 1 30); do
          if /usr/local/bin/k3s kubectl get nodes | grep -q Ready; then
            echo "节点已就绪"
            break
          fi
          echo "等待节点就绪... $i/30"
          sleep 2
        done
        
        echo -e "\n=== K3s 状态 ==="
        systemctl status k3s --no-pager
        
        echo -e "\n=== 节点状态 ==="
        /usr/local/bin/k3s kubectl get nodes
        
        echo -e "\n=== Pod 状态 ==="
        /usr/local/bin/k3s kubectl get pods --all-namespaces
      register: restart_result

    - name: 显示重启结果
      debug:
        msg: "{{ restart_result.stdout_lines | default([]) }}" 