---
- name: 测试 AWX 和 K3s 连接
  hosts: all
  gather_facts: no
  tasks:
    - name: 获取系统信息
      shell: |
        echo "=== 系统信息 ==="
        uname -a
        
        echo -e "\n=== 主机环境 ==="
        pwd
        whoami
        id
        
        echo -e "\n=== 检查 K3s 文件 ==="
        ls -l /usr/local/bin/k3s || echo "K3s 二进制文件不存在"
        ls -l /etc/rancher/k3s/k3s.yaml || echo "K3s 配置文件不存在"
        
        echo -e "\n=== 检查权限 ==="
        id
        groups
      register: system_info

    - name: 显示系统信息
      debug:
        msg: "{{ system_info.stdout_lines | default([]) }}" 