---
- name: Test target host connectivity and gather system information
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ping target host
      ping:

    - name: Get system information
      debug:
        msg: |
          === 基础系统信息 ===
          操作系统: {{ ansible_distribution }} {{ ansible_distribution_version }}
          内核版本: {{ ansible_kernel }}
          架构: {{ ansible_architecture }}
          CPU核心数: {{ ansible_processor_cores }}
          总内存: {{ ansible_memtotal_mb }}MB
          可用内存: {{ ansible_memory_mb.nocache.free }}MB
          
          === 网络信息 ===
          主机名: {{ ansible_hostname }}
          默认IPv4: {{ ansible_default_ipv4.address | default('Not set') }}
          DNS服务器: {{ ansible_dns.nameservers | join(', ') }}

    - name: Check K3s status
      shell: systemctl status k3s
      register: k3s_status
      ignore_errors: yes
      changed_when: false

    - name: Display K3s status
      debug:
        msg: "K3s 状态: {{ 'Active' if k3s_status.rc == 0 else 'Inactive or not installed' }}"

    - name: Check available ports
      shell: |
        netstat -tuln | grep -E ':(80|443|6443|30000|32767)' || true
      register: port_status
      changed_when: false

    - name: Display port status
      debug:
        msg: |
          === 端口状态 ===
          {{ port_status.stdout_lines | join('\n') }}

    - name: Check storage information
      shell: |
        df -h / /var/lib/rancher/k3s /var/lib/kubelet || true
      register: storage_info
      changed_when: false

    - name: Display storage information
      debug:
        msg: |
          === 存储信息 ===
          {{ storage_info.stdout_lines | join('\n') }}

    - name: Check container runtime
      shell: which docker containerd crio 2>/dev/null || true
      register: container_runtime
      changed_when: false

    - name: Display container runtime
      debug:
        msg: |
          === 容器运行时 ===
          已安装: {{ container_runtime.stdout_lines | join(', ') if container_runtime.stdout_lines else 'None' }}

    - name: Check required packages
      package_facts:
        manager: auto

    - name: Display package information
      debug:
        msg: |
          === 软件包状态 ===
          Nginx: {{ 'nginx' in ansible_facts.packages | string }}
          Python3: {{ 'python3' in ansible_facts.packages | string }}
          curl: {{ 'curl' in ansible_facts.packages | string }}
          wget: {{ 'wget' in ansible_facts.packages | string }}