---
- name: 测试 AWX 和 K3s 连接
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查基本连接
      shell: |
        echo "=== SSH 连接用户 ==="
        whoami
        id
        
        echo -e "\n=== 系统信息 ==="
        uname -a
        
        echo -e "\n=== 当前目录 ==="
        pwd
        
        echo -e "\n=== 环境变量 ==="
        env | grep -i user
        
        echo -e "\n=== 测试 K3s 命令 ==="
        /usr/local/bin/k3s kubectl get nodes || echo "无法执行 K3s 命令"
      register: system_info

    - name: 显示系统信息
      debug:
        msg: "{{ system_info.stdout_lines | default([]) }}"

    - name: 检查 K3s 状态
      shell: |
        echo "=== K3s 节点状态 ==="
        /usr/local/bin/k3s kubectl get nodes
        
        echo -e "\n=== K3s 系统 Pod ==="
        /usr/local/bin/k3s kubectl get pods -n kube-system
        
        echo -e "\n=== K3s 存储类 ==="
        /usr/local/bin/k3s kubectl get storageclass
        
        echo -e "\n=== K3s 版本信息 ==="
        /usr/local/bin/k3s --version
      register: k3s_info

    - name: 显示 K3s 信息
      debug:
        msg: "{{ k3s_info.stdout_lines | default([]) }}" 