---
- name: 测试 AWX 和 K3s 连接
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查 SSH 连接和用户权限
      shell: |
        echo "=== SSH 连接用户 ==="
        whoami
        echo "当前用户: $USER"
        
        echo -e "\n=== 系统信息 ==="
        uname -a
        
        echo -e "\n=== K3s 文件权限 ==="
        ls -l /usr/local/bin/k3s
        ls -l /etc/rancher/k3s/k3s.yaml
      register: system_info

    - name: 显示系统信息
      debug:
        msg: "{{ system_info.stdout_lines | default([]) }}"

    - name: 测试 K3s 命令
      shell: /usr/local/bin/k3s kubectl get nodes
      become: yes
      register: k3s_info

    - name: 显示 K3s 信息
      debug:
        msg: "{{ k3s_info.stdout_lines | default([]) }}" 