---
- name: 卸载 OpenSearch
  hosts: all
  gather_facts: no
  vars:
    default_namespace: default
  tasks:
    - name: 设置命名空间
      set_fact:
        use_namespace: "{{ namespace if namespace is defined else default_namespace }}"

    - name: 删除 OpenSearch 服务
      shell: |
        echo "=== 删除 OpenSearch 资源 ==="
        /usr/local/bin/k3s kubectl delete deployment,svc -l app=opensearch -n {{ use_namespace }} --force --grace-period=0 || true
        
        echo -e "\n=== 等待资源终止 ==="
        for i in {1..10}; do
          if ! /usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=opensearch 2>/dev/null | grep -q .; then
            echo "所有 Pod 已终止"
            break
          fi
          echo "等待 Pod 终止... $i"
          echo "仍在运行的 Pod:"
          /usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=opensearch
          sleep 3
        done
        
        echo -e "\n=== 清理数据目录 ==="
        rm -rf /data/opensearch || true
        
        echo -e "\n=== 验证清理结果 ==="
        echo "检查命名空间中的 OpenSearch 资源:"
        /usr/local/bin/k3s kubectl get all -n {{ use_namespace }} -l app=opensearch || echo "没有找到 OpenSearch 资源"
        
        echo -e "\n=== 检查端口占用 ==="
        /usr/local/bin/k3s kubectl get svc -n {{ use_namespace }} | grep "30920" || echo "没有服务使用端口 30920"
      register: uninstall_result

    - name: 显示卸载结果
      debug:
        msg: "{{ uninstall_result.stdout_lines }}" 