---
- name: 卸载 Percona
  hosts: all
  gather_facts: no
  tasks:
    - name: 删除 Percona 服务
      shell: |
        echo "=== 删除 Percona ==="
        # 强制删除所有相关资源
        /usr/local/bin/k3s kubectl delete deployment,svc,pvc,pv -l app=percona -n magento --force --grace-period=0 || true
        
        echo -e "\n=== 等待资源终止 ==="
        for i in {1..10}; do
          if ! /usr/local/bin/k3s kubectl get pods,svc -n magento -l app=percona 2>/dev/null | grep -q .; then
            echo "所有 Percona 资源已终止"
            break
          fi
          echo "等待资源终止... $i"
          sleep 3
        done

        echo -e "\n=== 清理数据目录 ==="
        rm -rf /data/percona || true
        
        echo -e "\n=== 验证清理结果 ==="
        echo "检查 Pods:"
        /usr/local/bin/k3s kubectl get pods -n magento -l app=percona
        echo "检查 Services:"
        /usr/local/bin/k3s kubectl get svc -n magento -l app=percona
        echo "检查 PVCs:"
        /usr/local/bin/k3s kubectl get pvc -n magento -l app=percona
      register: uninstall_result

    - name: 显示卸载结果
      debug:
        msg: "{{ uninstall_result.stdout_lines | default([]) }}" 