---
- name: 卸载 K3s
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查 K3s 状态
      shell: |
        echo "=== 当前 K3s 状态 ==="
        systemctl status k3s || echo "K3s 服务未运行"
      register: k3s_status
      ignore_errors: yes

    - name: 显示当前状态
      debug:
        msg: "{{ k3s_status.stdout_lines | default([]) }}"

    - name: 运行 K3s 卸载脚本
      shell: |
        if [ -f /usr/local/bin/k3s-uninstall.sh ]; then
          /usr/local/bin/k3s-uninstall.sh
        else
          echo "卸载脚本不存在"
          exit 1
        fi
      become: yes
      register: uninstall_result
      ignore_errors: yes

    - name: 清理 kubectl 配置
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ~/.kube/config
        - ~/.kube
      ignore_errors: yes

    - name: 验证卸载结果
      shell: |
        echo "=== 检查 K3s 服务 ==="
        systemctl status k3s || echo "K3s 服务已移除"
        
        echo -e "\n=== 检查 K3s 二进制文件 ==="
        ls -l /usr/local/bin/k3s || echo "K3s 二进制文件已移除"
        
        echo -e "\n=== 检查 K3s 配置目录 ==="
        ls -l /etc/rancher/k3s || echo "K3s 配置目录已移除"
      register: check_result
      ignore_errors: yes

    - name: 显示卸载结果
      debug:
        msg: "{{ check_result.stdout_lines | default([]) }}" 