---
- name: 诊断 PHP-FPM 问题
  hosts: all
  gather_facts: no
  tasks:
    - name: 获取所有命名空间
      shell: |
        kubectl get namespaces -o jsonpath='{.items[*].metadata.name}'
      register: namespaces_result

    - name: 设置命名空间列表
      set_fact:
        all_namespaces: "{{ namespaces_result.stdout.split() }}"

    - name: 显示诊断信息
      debug:
        msg: "开始检查所有命名空间中的 PHP-FPM"

    - name: 检查每个命名空间中的 PHP-FPM
      shell: |
        set -x
        NAMESPACE="{{ item }}"
        echo "=== 检查命名空间: $NAMESPACE ==="
        
        # 检查是否存在 PHP-FPM Pod
        if ! kubectl get pods -n "$NAMESPACE" -l app=php-fpm --no-headers 2>/dev/null | grep -q .; then
          echo "此命名空间中没有 PHP-FPM Pod"
          exit 0
        fi
        
        echo "=== 获取 Pod 信息 ==="
        POD_NAME=$(kubectl get pods -n "$NAMESPACE" -l app=php-fpm -o jsonpath='{.items[0].metadata.name}')
        echo "Pod 名称: $POD_NAME"
        
        echo "=== Pod 状态信息 ==="
        kubectl get pod -n "$NAMESPACE" "$POD_NAME" -o wide
        
        echo "=== Pod 详细信息 ==="
        kubectl describe pod -n "$NAMESPACE" "$POD_NAME" | grep -A 5 "Status:"
        
        echo "=== Pod 事件 ==="
        kubectl get events -n "$NAMESPACE" --field-selector involvedObject.name="$POD_NAME" --sort-by='.lastTimestamp' | tail -n 5
        
        echo "=== 容器日志 ==="
        echo "PHP-FPM 日志:"
        kubectl logs -n "$NAMESPACE" "$POD_NAME" --tail=20 || true
        
        if kubectl get pod -n "$NAMESPACE" "$POD_NAME" -o jsonpath='{.spec.initContainers[*].name}' 2>/dev/null | grep -q "init-php"; then
          echo "初始化容器日志:"
          kubectl logs -n "$NAMESPACE" "$POD_NAME" -c init-php --tail=20 || true
        fi
        
        echo "=== PHP 状态检查 ==="
        if kubectl get pod -n "$NAMESPACE" "$POD_NAME" -o jsonpath='{.status.phase}' | grep -q "Running"; then
          echo "PHP 版本:"
          kubectl exec -n "$NAMESPACE" "$POD_NAME" -- php -v || true
          echo "已安装扩展:"
          kubectl exec -n "$NAMESPACE" "$POD_NAME" -- php -m || true
        else
          echo "Pod 未处于运行状态，无法执行 PHP 命令"
        fi
        
        echo "=== 服务状态 ==="
        kubectl get svc -n "$NAMESPACE" -l app=php-fpm -o wide
        
        echo "----------------------------------------"
      register: check_result
      loop: "{{ all_namespaces }}"
      ignore_errors: yes

    - name: 显示诊断结果
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ check_result.results }}"
      when: item.stdout is defined 