---
- name: 诊断 OpenSearch 问题
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('magento-shared') }}"
  tasks:
    - name: 检查 OpenSearch 状态
      shell: |
        set -x
        echo "=== 开始诊断 OpenSearch ==="
        
        echo "获取 Pod 信息..."
        POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=opensearch -o jsonpath='{.items[0].metadata.name}')
        echo "Pod 名称: $POD_NAME"
        
        echo "=== Pod 详细信息 ==="
        kubectl describe pod -n {{ use_namespace }} $POD_NAME
        
        echo "=== Pod 日志 ==="
        kubectl logs -n {{ use_namespace }} $POD_NAME
        
        echo "=== 系统资源使用情况 ==="
        kubectl top pod -n {{ use_namespace }} $POD_NAME || true
        
        echo "=== 尝试重启 Pod ==="
        kubectl delete pod -n {{ use_namespace }} $POD_NAME --force --grace-period=0
        
        echo "等待新 Pod 创建..."
        sleep 10
        
        echo "=== 检查新 Pod 状态 ==="
        NEW_POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=opensearch -o jsonpath='{.items[0].metadata.name}')
        kubectl get pod -n {{ use_namespace }} $NEW_POD_NAME -o wide
        
        echo "=== 等待 Pod 就绪 ==="
        kubectl wait --for=condition=ready pod -n {{ use_namespace }} -l app=opensearch --timeout=300s || true
        
        echo "=== 最终状态 ==="
        kubectl get pods -n {{ use_namespace }} -l app=opensearch -o wide
        
        echo "=== 检查服务状态 ==="
        kubectl get svc -n {{ use_namespace }} -l app=opensearch
        
        echo "=== 检查日志 ==="
        kubectl logs -n {{ use_namespace }} $NEW_POD_NAME
      register: check_result

    - name: 显示诊断结果
      debug:
        msg: "{{ check_result.stdout_lines }}" 