---
all:
  children:
    k3s:
      hosts:
        k3s-master:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_become: yes
        ansible_become_method: sudo 