---
- name: 搜索 Galaxy 角色
  hosts: all
  vars:
    search_keyword: "{{ keyword | default('') }}"
  
  tasks:
    - name: 验证搜索关键词
      fail:
        msg: "必须指定 keyword 参数"
      when: search_keyword == ''

    - name: 搜索角色
      shell: |
        echo "=== 搜索 {{ search_keyword }} 相关的角色 ==="
        ansible-galaxy search {{ search_keyword }} --platforms EL,Debian | grep -v DEPRECATED
      register: search_result

    - name: 显示搜索结果
      debug:
        var: search_result.stdout_lines 