---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-service-account
  namespace: magento-shared

---
# 永久 Token
apiVersion: v1
kind: Secret
metadata:
  name: awx-service-account-token
  namespace: magento-shared
  annotations:
    kubernetes.io/service-account.name: awx-service-account
type: kubernetes.io/service-account-token

---
# ClusterRole (已存在，但为了完整性包含在这里)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awx-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "configmaps", "pods", "services", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awx-service-account-binding
subjects:
- kind: ServiceAccount
  name: awx-service-account
  namespace: magento-shared
roleRef:
  kind: ClusterRole
  name: awx-cluster-role
  apiGroup: rbac.authorization.k8s.io 