---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-service-account
  namespace: magento-shared

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awx-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awx-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: awx-service-account
  namespace: magento-shared
roleRef:
  kind: ClusterRole
  name: awx-cluster-role
  apiGroup: rbac.authorization.k8s.io 