---
- name: 检查所有命名空间的 Nginx 资源
  hosts: all
  gather_facts: no
  tasks:
    - name: 列出所有命名空间
      shell: |
        echo "=== 列出所有命名空间 ==="
        kubectl get ns
        
        echo -e "\n=== 列出所有命名空间中的 Nginx Pod ==="
        for ns in $(kubectl get ns -o jsonpath='{.items[*].metadata.name}'); do
          echo -e "\n命名空间: $ns"
          kubectl get pods -n $ns | grep -i nginx || echo "没有 Nginx Pod"
        done
        
        echo -e "\n=== 列出所有命名空间中的 Nginx Service ==="
        for ns in $(kubectl get ns -o jsonpath='{.items[*].metadata.name}'); do
          echo -e "\n命名空间: $ns"
          kubectl get svc -n $ns | grep -i nginx || echo "没有 Nginx Service"
        done
        
        echo -e "\n=== 列出所有命名空间中的 Nginx Ingress ==="
        for ns in $(kubectl get ns -o jsonpath='{.items[*].metadata.name}'); do
          echo -e "\n命名空间: $ns"
          kubectl get ingress -n $ns | grep -i nginx || echo "没有 Nginx Ingress"
        done
        
        echo -e "\n=== 列出所有 IngressClass ==="
        kubectl get ingressclass
      register: nginx_check

    - name: 显示检查结果
      debug:
        var: nginx_check.stdout_lines

    - name: 检查网络连接
      shell: |
        echo "=== 检查网络连接 ==="
        echo "检查 80 端口..."
        nc -zv awx.tschenfeng.com 80 || echo "80 端口连接失败"
        
        echo -e "\n检查 443 端口..."
        nc -zv awx.tschenfeng.com 443 || echo "443 端口连接失败"
      register: network_check

    - name: 显示网络检查结果
      debug:
        var: network_check.stdout_lines 