---
- name: 检查 Nginx Ingress Controller 状态
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查 Ingress Controller Pod
      shell: |
        echo "=== 检查 Ingress Controller Pod ==="
        kubectl get pods -n ingress-nginx
        
        echo -e "\n=== 检查 Ingress Controller 服务 ==="
        kubectl get svc -n ingress-nginx
        
        echo -e "\n=== 检查 Ingress Controller 配置 ==="
        kubectl get ingressclass
        
        echo -e "\n=== 检查 Ingress Controller Pod 日志 ==="
        NGINX_POD=$(kubectl get pods -n ingress-nginx -l app.kubernetes.io/component=controller -o jsonpath='{.items[0].metadata.name}')
        if [ ! -z "$NGINX_POD" ]; then
          kubectl logs -n ingress-nginx $NGINX_POD --tail=50
        else
          echo "未找到 Ingress Controller Pod"
        fi
      register: ingress_check

    - name: 显示检查结果
      debug:
        var: ingress_check.stdout_lines

    - name: 检查网络连接
      shell: |
        echo "=== 检查网络连接 ==="
        echo "检查 80 端口..."
        nc -zv awx.tschenfeng.com 80 || echo "80 端口连接失败"
        
        echo -e "\n检查 443 端口..."
        nc -zv awx.tschenfeng.com 443 || echo "443 端口连接失败"
      register: network_check

    - name: 显示网络检查结果
      debug:
        var: network_check.stdout_lines 