---
- name: 检查 cert-manager 状态
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查证书状态
      shell: |
        echo "=== 检查 cert-manager Pod 状态 ==="
        kubectl get pods -n cert-manager
        
        echo -e "\n=== 检查 ClusterIssuer 状态 ==="
        kubectl get clusterissuer letsencrypt-prod -o yaml
        
        echo -e "\n=== 检查证书状态 ==="
        kubectl get certificate -n awx
        
        echo -e "\n=== 检查证书详细信息 ==="
        kubectl describe certificate awx-tls -n awx
        
        echo -e "\n=== 检查 CertificateRequest ==="
        kubectl get certificaterequest -n awx
        
        echo -e "\n=== 检查 Order 状态 ==="
        kubectl get order -n awx
        
        echo -e "\n=== 检查 Challenge 状态 ==="
        kubectl get challenge -n awx
        
        echo -e "\n=== 检查 Ingress 配置 ==="
        kubectl get ingress -n awx
      register: cert_status

    - name: 显示检查结果
      debug:
        var: cert_status.stdout_lines 