---
- name: 配置 cert-manager 证书
  hosts: all
  gather_facts: yes
  vars:
    domain_name: awx.tschenfeng.com
    email_address: ssl@tschenfeng.com
    cluster_issuer_name: letsencrypt-prod
    staging: true   # 使用 Let's Encrypt 测试环境，避免触发生产环境速率限制

  tasks:
    - name: 检查和配置 K3s kubeconfig
      shell: |
        echo "检查 K3s kubeconfig..."
        if [ -f /etc/rancher/k3s/k3s.yaml ]; then
          echo "找到 K3s kubeconfig"
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          chmod 644 ~/.kube/config
          echo "已复制 kubeconfig 到 ~/.kube/config"
        else
          echo "未找到 K3s kubeconfig"
          exit 1
        fi
        
        echo "测试 kubectl 连接..."
        kubectl cluster-info
      register: kube_check
      become: yes

    - name: 创建 Cloudflare API Token Secret
      shell: |
        # 创建包含 API Token 的文件，确保没有换行符
        echo -n "{{ cloudflare_api_token }}" > /tmp/cloudflare-api-token
        
        # 创建 Secret
        kubectl create secret generic cloudflare-api-token \
          --namespace cert-manager \
          --from-file=api-token=/tmp/cloudflare-api-token \
          --dry-run=client -o yaml | kubectl apply -f -
        
        # 清理临时文件
        rm -f /tmp/cloudflare-api-token
      register: secret_result

    - name: 显示 kubeconfig 检查结果
      debug:
        var: kube_check.stdout_lines

    - name: 创建 ClusterIssuer
      copy:
        dest: /tmp/cluster-issuer.yaml
        content: |
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: {{ cluster_issuer_name }}
          spec:
            acme:
              email: {{ email_address }}
              server: https://acme-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                name: letsencrypt-prod
              solvers:
                - dns01:
                    cloudflare:
                      email: {{ email_address }}
                      apiTokenSecretRef:
                        name: cloudflare-api-token
                        key: api-token

    - name: 应用 ClusterIssuer
      shell: kubectl apply -f /tmp/cluster-issuer.yaml

    - name: 配置 AWX Ingress
      copy:
        dest: /tmp/awx-ingress.yaml
        content: |
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: awx-ingress
            namespace: awx
            annotations:
              cert-manager.io/cluster-issuer: {{ cluster_issuer_name }}
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/ssl-redirect: "false"  # 暂时关闭 SSL 重定向，以允许 HTTP-01 验证
              acme.cert-manager.io/http01-edit-in-place: "true"  # 允许 cert-manager 直接编辑 Ingress 资源
              nginx.ingress.kubernetes.io/proxy-body-size: "64m"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          spec:
            tls:
            - hosts:
              - {{ domain_name }}
              secretName: awx-tls
            rules:
            - host: {{ domain_name }}
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: awx-service
                      port:
                        number: 80

    - name: 应用 AWX Ingress
      shell: kubectl apply -f /tmp/awx-ingress.yaml

    - name: 检查初始证书状态
      shell: |
        echo "=== 初始证书状态检查 ==="
        
        echo "检查 Cloudflare API Token Secret..."
        kubectl get secret cloudflare-api-token -n cert-manager -o yaml
        
        echo "检查 cert-manager 日志..."
        kubectl logs -n cert-manager -l app=cert-manager --tail=50
        
        echo "检查 ClusterIssuer 状态..."
        kubectl get clusterissuer {{ cluster_issuer_name }} -o wide
        
        echo "检查 Ingress 配置..."
        kubectl get ingress -n awx -o wide
        
        echo "检查证书申请状态..."
        echo "证书详细信息："
        kubectl get certificate -n awx -o yaml
        
        echo "证书请求详细信息："
        kubectl get certificaterequest -n awx -o yaml
        
        echo "ACME Order 详细信息："
        kubectl get order -n awx -o yaml
        
        echo "ACME Challenge 详细信息："
        kubectl get challenge -n awx -o yaml
        
        echo "Events 信息："
        kubectl get events -n awx --sort-by='.lastTimestamp'
      register: initial_status
      ignore_errors: yes

    - name: 显示初始状态
      debug:
        msg: "{{ initial_status.stdout_lines }}"

    - name: 等待证书就绪
      shell: |
        kubectl wait --for=condition=ready certificate awx-tls -n awx --timeout=300s
      register: cert_wait_result
      until: cert_wait_result.rc == 0
      retries: 30
      delay: 10

    - name: 验证证书状态
      shell: |
        echo "=== 证书状态检查 ==="
        echo "检查证书状态..."
        kubectl get certificate awx-tls -n awx -o wide
        
        echo "检查证书请求状态..."
        kubectl get certificaterequest -n awx -o wide
        
        echo "检查 ACME orders..."
        kubectl get order -n awx -o wide
        
        echo "检查 ACME challenges..."
        kubectl get challenge -n awx -o wide
        
        echo "检查证书 Secret..."
        kubectl get secret awx-tls -n awx -o jsonpath='{.metadata.annotations}' | grep cert-manager
      register: cert_status
      
    - name: 显示证书状态
      debug:
        msg: "{{ cert_status.stdout_lines }}"

    - name: 显示配置完成信息
      debug:
        msg: |
          证书配置已完成！
          域名: {{ domain_name }}
          ClusterIssuer: {{ cluster_issuer_name }}
          证书名称: awx-tls
          命名空间: awx 