---
- name: 配置站点 Redis 数据库
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('default') }}"
    site_name: "{{ site | mandatory }}"  # 必须提供站点名称
    db_offset: "{{ offset | default(0) | int }}"  # 数据库偏移量，默认从 0 开始
  tasks:
    - name: 显示 Redis 数据库分配
      debug:
        msg: |
          站点: {{ site_name }}
          数据库分配:
            - 默认缓存: {{ db_offset }}
            - 页面缓存: {{ db_offset + 1 }}
            - 会话存储: {{ db_offset + 2 }}

    - name: 检查 Redis 是否运行
      shell: |
        echo "=== 检查 Redis 状态 ==="
        POD_NAME=$(/usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=redis -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$POD_NAME" ]; then
          echo "错误: Redis Pod 不存在"
          exit 1
        fi
        
        POD_STATUS=$(/usr/local/bin/k3s kubectl get pod $POD_NAME -n {{ use_namespace }} -o jsonpath='{.status.phase}')
        if [ "$POD_STATUS" != "Running" ]; then
          echo "错误: Redis Pod 未运行，状态: $POD_STATUS"
          exit 1
        fi
        
        echo "Redis 运行正常: $POD_NAME"
      register: redis_status

    - name: 显示 Redis 状态
      debug:
        var: redis_status.stdout_lines

    - name: 初始化数据库
      shell: |
        echo "=== 初始化数据库 ==="
        POD_NAME=$(/usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=redis -o jsonpath='{.items[0].metadata.name}')
        
        # 清理数据库
        echo "清理数据库 {{ db_offset }}-{{ db_offset + 2 }}..."
        for db in $(seq {{ db_offset }} {{ db_offset + 2 }}); do
          echo "清理数据库 $db"
          /usr/local/bin/k3s kubectl exec -n {{ use_namespace }} $POD_NAME -- redis-cli select $db
          /usr/local/bin/k3s kubectl exec -n {{ use_namespace }} $POD_NAME -- redis-cli flushdb
        done
        
        echo "数据库初始化完成"
      register: init_result

    - name: 显示初始化结果
      debug:
        var: init_result.stdout_lines

    - name: 创建数据库使用说明
      copy:
        dest: "/tmp/redis-{{ site_name }}.txt"
        content: |
          Redis 数据库分配 - {{ site_name }}
          ============================
          
          默认缓存: 数据库 {{ db_offset }}
          页面缓存: 数据库 {{ db_offset + 1 }}
          会话存储: 数据库 {{ db_offset + 2 }}
          
          连接信息:
          - 主机: redis.{{ use_namespace }}.svc.cluster.local
          - 端口: 6379
          - NodePort: 30379
          
          示例配置:
          ```xml
          <cache>
             <backend>Redis</backend>
             <backend_options>
                 <server>redis.{{ use_namespace }}.svc.cluster.local</server>
                 <port>6379</port>
                 <database>{{ db_offset }}</database>
             </backend_options>
          </cache>
          ``` 