---
- name: 配置 PHP-FPM 性能参数
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('default') }}"
    max_children: "{{ pm_max_children | default('50') }}"
    start_servers: "{{ pm_start_servers | default('5') }}"
    min_spare_servers: "{{ pm_min_spare_servers | default('5') }}"
    max_spare_servers: "{{ pm_max_spare_servers | default('35') }}"
    max_requests: "{{ pm_max_requests | default('500') }}"

  tasks:
    - name: 获取 PHP-FPM Pod 名称
      shell: |
        set -x  # 启用调试模式
        POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=php-fpm -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$POD_NAME" ]; then
          echo "未找到 PHP-FPM Pod"
          exit 1
        fi
        echo $POD_NAME
      register: pod_name

    - name: 检查 Pod 状态
      shell: |
        set -x  # 启用调试模式
        POD_NAME="{{ pod_name.stdout }}"
        echo "检查 Pod $POD_NAME 状态..."
        
        # 显示 Pod 详细信息
        echo "Pod 详细信息:"
        kubectl describe pod -n {{ use_namespace }} $POD_NAME
        
        # 检查 Pod 状态
        STATUS=$(kubectl get pod -n {{ use_namespace }} $POD_NAME -o jsonpath='{.status.phase}')
        echo "Pod 状态: $STATUS"
        
        if [ "$STATUS" != "Running" ]; then
          echo "Pod 未处于运行状态"
          exit 1
        fi
      register: pod_status

    - name: 显示 Pod 状态
      debug:
        msg: "{{ pod_status.stdout_lines }}"

    - name: 配置 PHP-FPM
      shell: |
        set -x  # 启用调试模式
        POD_NAME="{{ pod_name.stdout }}"
        echo "=== 配置 PHP-FPM ==="
        
        # 切换到 root 用户并执行命令
        kubectl exec -n {{ use_namespace }} $POD_NAME -- bash << 'EOF'
        set -x  # 启用调试模式
        
        # 检查当前用户
        echo "当前用户:"
        whoami
        
        # 创建配置目录
        echo "创建配置目录..."
        mkdir -p /usr/local/etc/php-fpm.d
        
        # 配置 PHP-FPM
        echo "配置 PHP-FPM..."
        cat > /usr/local/etc/php-fpm.d/www.conf << 'EOC'
        [www]
        user = www-data
        group = www-data
        
        ; 动态进程管理 - Magento 2 优化
        pm = dynamic
        pm.max_children = {{ max_children }}      ; 根据服务器内存调整：(Total RAM - Reserved RAM) / Process Size
        pm.start_servers = {{ start_servers }}    ; 通常设置为 max_children 的 10%
        pm.min_spare_servers = {{ min_spare_servers }}  ; 与 start_servers 相同
        pm.max_spare_servers = {{ max_spare_servers }}  ; 通常设置为 max_children 的 70%
        pm.max_requests = {{ max_requests }}      ; 防止内存泄漏
        
        ; 请求超时设置 - Magento 2 优化
        request_terminate_timeout = 600s          ; 长时间运行的进程（如导入）
        request_slowlog_timeout = 10s             ; Magento 2 后台操作可能较慢
        slowlog = /proc/self/fd/2
        
        ; 错误日志
        php_admin_flag[log_errors] = on
        php_admin_value[error_log] = /proc/self/fd/2
        
        ; 缓冲区设置 - Magento 2 优化
        php_admin_value[memory_limit] = 2G        ; Magento 2 推荐
        php_admin_value[max_execution_time] = 600 ; 长时间运行的进程
        php_admin_value[max_input_time] = 600     ; 文件上传等操作
        php_admin_value[post_max_size] = 64M      ; 大文件上传
        php_admin_value[upload_max_filesize] = 64M ; 大文件上传
        
        ; 会话处理 - Magento 2 优化
        php_value[session.gc_maxlifetime] = 86400  ; 会话过期时间
        php_value[session.gc_probability] = 1
        php_value[session.gc_divisor] = 1000
        
        ; 其他优化
        pm.process_idle_timeout = 10s
        pm.status_path = /status
        ping.path = /ping
        ping.response = pong
        
        ; 环境变量
        env[HOSTNAME] = $HOSTNAME
        env[PATH] = /usr/local/bin:/usr/bin:/bin
        
        ; OPcache 设置 - Magento 2 优化
        php_admin_value[opcache.memory_consumption] = 512      ; 更大的缓存
        php_admin_value[opcache.interned_strings_buffer] = 32  ; 更多字符串缓存
        php_admin_value[opcache.max_accelerated_files] = 60000 ; Magento 2 有很多文件
        php_admin_value[opcache.revalidate_freq] = 2          ; 生产环境推荐
        php_admin_value[opcache.fast_shutdown] = 1
        php_admin_value[opcache.enable_cli] = 1               ; CLI 模式也启用缓存
        php_admin_value[opcache.save_comments] = 1            ; Magento 2 需要注释
        php_admin_value[opcache.enable_file_override] = 0     ; 生产环境推荐
        php_admin_value[opcache.validate_timestamps] = 0      ; 生产环境推荐
        
        ; Realpath 缓存 - Magento 2 优化
        php_admin_value[realpath_cache_size] = 10M
        php_admin_value[realpath_cache_ttl] = 7200
        
        ; 输入变量限制 - Magento 2 优化
        php_admin_value[max_input_vars] = 10000    ; 复杂表单提交
        EOC
        
        # 验证配置
        echo "验证配置..."
        php-fpm -t
        EOF
      register: config_result

    - name: 显示配置结果
      debug:
        msg: "{{ config_result.stdout_lines }}"

    - name: 重启 PHP-FPM
      shell: |
        set -x  # 启用调试模式
        POD_NAME="{{ pod_name.stdout }}"
        echo "=== 重启 PHP-FPM ==="
        
        # 切换到 root 用户并执行命令
        kubectl exec -n {{ use_namespace }} $POD_NAME -- bash << 'EOF'
        set -x  # 启用调试模式
        
        # 检查当前用户
        echo "当前用户:"
        whoami
        
        # 重启 PHP-FPM
        echo "重启 PHP-FPM..."
        kill -USR2 1
        EOF
      register: restart_result

    - name: 显示重启结果
      debug:
        msg: "{{ restart_result.stdout_lines }}"

    - name: 验证 PHP-FPM 状态
      shell: |
        set -x  # 启用调试模式
        POD_NAME="{{ pod_name.stdout }}"
        echo "=== 验证 PHP-FPM 状态 ==="
        
        # 等待 PHP-FPM 重启
        echo "等待 PHP-FPM 重启..."
        sleep 5
        
        # 检查进程
        echo "检查 PHP-FPM 进程..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- ps aux | grep php-fpm
      register: verify_result

    - name: 显示验证结果
      debug:
        msg: "{{ verify_result.stdout_lines }}" 