---
- name: 部署 Nginx 到 K3s
  hosts: all
  gather_facts: no
  tasks:
    - name: 确保 K3s 正在运行
      shell: |
        systemctl is-active k3s
      register: k3s_status
      ignore_errors: yes

    - name: 检查 K3s 状态
      fail:
        msg: "K3s 未运行，请先安装并启动 K3s"
      when: k3s_status.rc != 0

    - name: 创建 Nginx 部署配置
      copy:
        src: nginx-deployment.yml
        dest: /tmp/nginx-deployment.yml

    - name: 部署 Nginx
      shell: |
        KUBECONFIG=/etc/rancher/k3s/k3s.yaml k3s kubectl apply -f /tmp/nginx-deployment.yml
      register: deploy_result

    - name: 等待 Nginx Pod 就绪
      shell: |
        for i in {1..30}; do
          if KUBECONFIG=/etc/rancher/k3s/k3s.yaml k3s kubectl get pods | grep nginx-deployment | grep Running; then
            echo "Nginx Pod 已就绪"
            exit 0
          fi
          echo "等待 Nginx Pod 就绪... $i"
          sleep 2
        done
        echo "Nginx Pod 启动超时"
        exit 1
      register: nginx_wait
      ignore_errors: yes

    - name: 获取 Nginx 访问信息
      shell: |
        echo "=== Nginx Pod 状态 ==="
        KUBECONFIG=/etc/rancher/k3s/k3s.yaml k3s kubectl get pods | grep nginx
        
        echo -e "\n=== Nginx Service 状态 ==="
        KUBECONFIG=/etc/rancher/k3s/k3s.yaml k3s kubectl get svc nginx-service
        
        echo -e "\n=== Nginx Ingress 状态 ==="
        KUBECONFIG=/etc/rancher/k3s/k3s.yaml k3s kubectl get ingress nginx-ingress
      register: nginx_status
      ignore_errors: yes

    - name: 显示 Nginx 状态
      debug:
        msg: "{{ nginx_status.stdout_lines | default([]) }}" 