---
- name: 安装 PHP-FPM 8.3 基础环境
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace }}"
    use_nodeport: "{{ nodeport | default('9000') }}"
    max_retries: "{{ retries | default('3') }}"
    init_delay: "{{ delay | default('30') }}"

  tasks:
    - name: 检查命名空间
      shell: |
        set -x  # 启用调试模式
        set -e  # 遇到错误就退出
        
        if [ "{{ use_namespace }}" != "default" ]; then
          echo "创建命名空间: {{ use_namespace }}"
          kubectl create namespace {{ use_namespace }} || true
        else
          echo "使用默认命名空间"
        fi

    - name: 创建 PHP-FPM 基础配置
      shell: |
        cat > /tmp/php-fpm.yaml << 'EOF'
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: php-fpm
          namespace: {{ use_namespace }}
          labels:
            app: php-fpm
        spec:
          selector:
            matchLabels:
              app: php-fpm
          replicas: 1
          template:
            metadata:
              labels:
                app: php-fpm
            spec:
              securityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
              containers:
              - name: php-fpm
                image: php:8.3-fpm
                securityContext:
                  privileged: true
                  allowPrivilegeEscalation: true
                ports:
                - containerPort: 9000
                resources:
                  requests:
                    cpu: "500m"
                    memory: "512Mi"
                  limits:
                    cpu: "1"
                    memory: "1Gi"
                readinessProbe:
                  tcpSocket:
                    port: 9000
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  successThreshold: 1
                  failureThreshold: 3
                livenessProbe:
                  tcpSocket:
                    port: 9000
                  initialDelaySeconds: 60
                  periodSeconds: 20
                  timeoutSeconds: 5
                  successThreshold: 1
                  failureThreshold: 3
                volumeMounts:
                - name: shared-data
                  mountPath: /var/www/html
                - name: php-fpm-config
                  mountPath: /usr/local/etc/php-fpm.d/www.conf
                  subPath: www.conf
              volumes:
              - name: shared-data
                emptyDir: {}
              - name: php-fpm-config
                configMap:
                  name: php-fpm-config
        ---
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: php-fpm-config
          namespace: {{ use_namespace }}
        data:
          www.conf: |
            [www]
            user = www-data
            group = www-data
            listen = 9000
            pm = dynamic
            pm.max_children = 5
            pm.start_servers = 2
            pm.min_spare_servers = 1
            pm.max_spare_servers = 3
            pm.max_requests = 500
            catch_workers_output = yes
            php_admin_value[error_log] = /proc/self/fd/2
            php_admin_flag[log_errors] = on
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: php-fpm
          namespace: {{ use_namespace }}
          labels:
            app: php-fpm
        spec:
          selector:
            app: php-fpm
          ports:
          - name: fpm
            port: 9000
            targetPort: 9000
          type: ClusterIP
        EOF

    - name: 清理旧部署
      shell: |
        kubectl delete -f /tmp/php-fpm.yaml || true
        echo "等待旧资源清理完成..."
        sleep 10

    - name: 应用 PHP-FPM 配置
      shell: |
        set -x  # 启用调试模式
        
        echo "=== 应用配置 ==="
        kubectl apply -f /tmp/php-fpm.yaml
        
        echo "=== 等待 Pod 创建 ==="
        for i in $(seq 1 {{ max_retries }}); do
          echo "检查 Pod 创建进度... 第 $i 次"
          
          # 显示所有 Pod
          echo "当前所有 Pod:"
          kubectl get pods -n {{ use_namespace }} -o wide
          
          # 检查特定 Pod
          if kubectl get pods -n {{ use_namespace }} -l app=php-fpm --no-headers | grep -q .; then
            echo "Pod 已创建"
            break
          fi
          
          if [ $i -eq {{ max_retries }} ]; then
            echo "Pod 创建超时"
            echo "查看部署状态:"
            kubectl get deployment -n {{ use_namespace }} php-fpm -o yaml
            echo "查看事件:"
            kubectl get events -n {{ use_namespace }} --sort-by='.lastTimestamp'
            exit 1
          fi
          
          echo "等待下一次检查..."
          sleep {{ init_delay }}
        done
        
        echo "=== 检查 Pod 状态 ==="
        POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=php-fpm -o jsonpath='{.items[0].metadata.name}')
        echo "Pod 名称: $POD_NAME"
        
        for i in $(seq 1 {{ max_retries }}); do
          echo "检查 Pod 状态... 第 $i 次"
          
          # 显示 Pod 详情
          echo "Pod 详细信息:"
          kubectl describe pod -n {{ use_namespace }} $POD_NAME
          
          # 检查 Pod 状态
          STATUS=$(kubectl get pod -n {{ use_namespace }} $POD_NAME -o jsonpath='{.status.phase}')
          echo "Pod 状态: $STATUS"
          
          if [ "$STATUS" = "Running" ]; then
            echo "Pod 已就绪"
            
            # 检查容器日志
            echo "容器日志:"
            kubectl logs -n {{ use_namespace }} $POD_NAME
            
            # 验证 PHP-FPM 是否正常运行
            echo "验证 PHP-FPM 状态..."
            if kubectl exec -n {{ use_namespace }} $POD_NAME -- bash -c 'ps aux | grep php-fpm'; then
              echo "PHP-FPM 进程正在运行"
              if kubectl exec -n {{ use_namespace }} $POD_NAME -- php-fpm -v; then
                echo "PHP-FPM 基础环境检查通过"
                break
              fi
            fi
          fi
          
          if [ $i -eq {{ max_retries }} ]; then
            echo "Pod 启动失败，当前状态: $STATUS"
            echo "查看事件:"
            kubectl get events -n {{ use_namespace }} --sort-by='.lastTimestamp'
            exit 1
          fi
          
          echo "当前状态: $STATUS，等待下一次检查..."
          sleep {{ init_delay }}
        done
      register: deploy_result

    - name: 显示部署结果
      debug:
        msg: "{{ deploy_result.stdout_lines }}" 