---
- name: 安装 cert-manager
  hosts: all
  gather_facts: yes
  vars:
    cert_manager_version: v1.13.0
    cert_manager_namespace: cert-manager

  tasks:
    - name: 检查和配置 K3s kubeconfig
      shell: |
        echo "检查 K3s kubeconfig..."
        if [ -f /etc/rancher/k3s/k3s.yaml ]; then
          echo "找到 K3s kubeconfig"
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          chmod 644 ~/.kube/config
          echo "已复制 kubeconfig 到 ~/.kube/config"
        else
          echo "未找到 K3s kubeconfig"
          exit 1
        fi
        
        echo "测试 kubectl 连接..."
        kubectl cluster-info
      register: kube_check
      become: yes

    - name: 显示 kubeconfig 检查结果
      debug:
        var: kube_check.stdout_lines

    - name: 检查 Helm 是否已安装
      shell: command -v helm || echo "not found"
      register: helm_check
      changed_when: false

    - name: 下载并安装 Helm
      shell: |
        set -e
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        rm -f get_helm.sh
      when: helm_check.stdout == "not found"

    - name: 创建 cert-manager 命名空间
      shell: |
        kubectl create namespace {{ cert_manager_namespace }} --dry-run=client -o yaml | kubectl apply -f -

    - name: 添加 Jetstack Helm 仓库
      shell: |
        helm repo add jetstack https://charts.jetstack.io
        helm repo update

    - name: 安装 cert-manager CRDs
      shell: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml

    - name: 安装 cert-manager
      shell: |
        helm upgrade --install \
          cert-manager jetstack/cert-manager \
          --namespace {{ cert_manager_namespace }} \
          --version {{ cert_manager_version }} \
          --set installCRDs=false \
          --wait

    - name: 等待 cert-manager 就绪
      shell: |
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/instance=cert-manager --namespace {{ cert_manager_namespace }} --timeout=300s
      register: wait_result
      until: wait_result.rc == 0
      retries: 30
      delay: 10

    - name: 显示安装完成信息
      debug:
        msg: |
          cert-manager 已安装完成！
          版本: {{ cert_manager_version }}
          命名空间: {{ cert_manager_namespace }} 