---
- name: 安装 Certbot
  hosts: all
  gather_facts: no
  become: yes
  vars:
    namespace: "{{ namespace | default('default') }}"  # 可在 AWX 中覆盖
    domain_name: "{{ domain_name }}"
    email_address: "{{ email_address }}"
    use_staging: "{{ staging | default(true) }}"  # 默认使用 staging 环境，避免触发限制
    webroot_path: "/var/www/certbot"
  
  tasks:
    - name: 获取 Nginx Pod 名称
      shell: |
        set -x
        echo "=== 获取 Nginx Pod ==="
        
        # 获取 Pod 名称
        POD_NAME=$(kubectl get pods -n {{ namespace }} -l app=nginx -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$POD_NAME" ]; then
          echo "未找到 Nginx Pod"
          exit 1
        fi
        echo $POD_NAME
      register: pod_name
      
    - name: 显示 Pod 信息
      debug:
        msg: "Nginx Pod: {{ pod_name.stdout }}"

    - name: 安装依赖
      shell: |
        set -x
        echo "=== 安装依赖 ==="
        
        # 更新包管理器
        apt-get update
        
        # 安装依赖
        apt-get install -y \
          python3-pip \
          python3-venv \
          snapd
        
        # 确保 snap 正常运行
        systemctl start snapd
        systemctl enable snapd
      register: deps_result
      
    - name: 显示依赖安装结果
      debug:
        msg: "{{ deps_result.stdout_lines }}"

    - name: 安装 certbot
      shell: |
        set -x
        echo "=== 安装 certbot ==="
        
        # 删除可能存在的旧版本
        apt-get remove -y certbot
        
        # 安装最新版本
        snap install --classic certbot
        
        # 创建软链接
        ln -sf /snap/bin/certbot /usr/bin/certbot
      register: install_result
      
    - name: 显示安装结果
      debug:
        msg: "{{ install_result.stdout_lines }}"

    - name: 创建 webroot 目录
      file:
        path: "{{ webroot_path }}"
        state: directory
        mode: '0755'
      become: true

    - name: 获取 nginx pod 名称
      shell: kubectl -n {{ namespace }} get pods -l app=nginx -o jsonpath='{.items[0].metadata.name}'
      register: nginx_pod
      changed_when: false

    - name: 在 nginx pod 中创建 webroot 目录
      shell: kubectl -n {{ namespace }} exec {{ nginx_pod.stdout }} -- mkdir -p {{ webroot_path }}
      ignore_errors: true

    - name: 配置 nginx 以服务验证文件
      copy:
        content: |
          # 临时配置，仅用于证书验证
          server {
            listen 80 default_server;
            server_name {{ domain_name }};
            
            # 用于 Let's Encrypt 验证
            location /.well-known/acme-challenge/ {
                root {{ webroot_path }};
            }

            # 暂时返回成功
            location / {
                return 200 'OK';
            }
          }
        dest: /tmp/certbot-location.conf
      become: true

    - name: 复制 nginx 配置到 pod
      shell: kubectl -n {{ namespace }} cp /tmp/certbot-location.conf {{ nginx_pod.stdout }}:/etc/nginx/conf.d/default.conf

    - name: 重新加载 nginx 配置
      shell: |
        set -x
        echo "=== 重新加载 Nginx 配置 ==="
        
        # 删除其他配置
        kubectl -n {{ namespace }} exec {{ nginx_pod.stdout }} -- rm -f /etc/nginx/conf.d/awx.conf || true
        
        # 测试配置
        kubectl -n {{ namespace }} exec {{ nginx_pod.stdout }} -- nginx -t
        
        # 重新加载
        kubectl -n {{ namespace }} exec {{ nginx_pod.stdout }} -- nginx -s reload

    - name: 申请证书
      shell: |
        set -x
        echo "=== 申请证书 ==="
        
        # 检查 webroot 目录
        echo "检查 webroot 目录..."
        ls -la {{ webroot_path }}
        
        # 检查 nginx 配置
        echo "检查 nginx 配置..."
        kubectl -n {{ namespace }} exec {{ nginx_pod.stdout }} -- nginx -T
        
        # 测试域名解析
        echo "测试域名解析..."
        host {{ domain_name }}
        
        # 测试 HTTP 访问
        echo "测试 HTTP 访问..."
        curl -v http://{{ domain_name }}/.well-known/acme-challenge/test
        
        # 申请证书
        echo "开始申请证书..."
        certbot certonly \
          --webroot \
          -w {{ webroot_path }} \
          -d {{ domain_name }} \
          --email {{ email_address }} \
          --agree-tos \
          --non-interactive \
          --debug-challenges \
          -v \
          {% if use_staging %}--staging{% endif %}
        
        # 检查证书
        echo "检查证书..."
        certbot certificates
        
        # 检查证书文件
        echo "检查证书文件..."
        ls -la /etc/letsencrypt/live/{{ domain_name }}/
      register: cert_result
      
    - name: 显示证书申请结果
      debug:
        msg: "{{ cert_result.stdout_lines }}"

    - name: 配置自动续期
      shell: |
        set -x
        echo "=== 配置自动续期 ==="
        
        # 测试自动续期
        certbot renew --dry-run {% if use_staging %}--staging{% endif %}
        
        # 添加续期前后的钩子
        mkdir -p /etc/letsencrypt/renewal-hooks/pre
        mkdir -p /etc/letsencrypt/renewal-hooks/post
        
        # 创建续期前停止 Nginx 的脚本
        cat > /etc/letsencrypt/renewal-hooks/pre/stop-nginx.sh << 'EOF'
        #!/bin/bash
        kubectl -n {{ namespace }} scale deployment nginx --replicas=0
        EOF
        
        # 创建续期后启动 Nginx 的脚本
        cat > /etc/letsencrypt/renewal-hooks/post/start-nginx.sh << 'EOF'
        #!/bin/bash
        kubectl -n {{ namespace }} scale deployment nginx --replicas=1
        EOF
        
        # 设置执行权限
        chmod +x /etc/letsencrypt/renewal-hooks/pre/stop-nginx.sh
        chmod +x /etc/letsencrypt/renewal-hooks/post/start-nginx.sh
      register: renew_result
      
    - name: 显示自动续期配置结果
      debug:
        msg: "{{ renew_result.stdout_lines }}"

    - name: 复制证书到 Nginx Pod
      shell: |
        set -x
        echo "=== 复制证书到 Nginx Pod ==="
        
        # 获取 Pod 名称
        POD_NAME=$(kubectl get pods -n {{ namespace }} -l app=nginx -o jsonpath='{.items[0].metadata.name}')
        echo "Pod 名称: $POD_NAME"
        
        # 检查源证书文件
        echo "检查源证书文件..."
        ls -la /etc/letsencrypt/live/{{ domain_name }}/
        
        # 创建 Pod 中的目录
        echo "创建证书目录..."
        kubectl -n {{ namespace }} exec $POD_NAME -- mkdir -p /etc/letsencrypt/live/{{ domain_name }}
        
        # 直接复制证书文件
        echo "复制证书文件..."
        for cert in fullchain.pem privkey.pem chain.pem; do
          echo "复制 $cert..."
          # 检查源文件
          ls -l /etc/letsencrypt/live/{{ domain_name }}/$cert
          # 复制文件
          kubectl -n {{ namespace }} cp /etc/letsencrypt/live/{{ domain_name }}/$cert {{ namespace }}/$POD_NAME:/etc/letsencrypt/live/{{ domain_name }}/$cert
          # 验证目标文件
          kubectl -n {{ namespace }} exec $POD_NAME -- ls -l /etc/letsencrypt/live/{{ domain_name }}/$cert
        done
        
        # 验证复制结果
        echo "验证证书文件..."
        kubectl -n {{ namespace }} exec $POD_NAME -- ls -la /etc/letsencrypt/live/{{ domain_name }}/
      register: copy_result
      
    - name: 显示复制结果
      debug:
        msg: "{{ copy_result.stdout_lines }}"

    - name: 配置自动续期
      ansible.builtin.cron:
        name: "certbot renew for {{ domain_name }}"
        job: "certbot renew --webroot -w {{ webroot_path }} --deploy-hook 'kubectl -n {{ namespace }} exec $(kubectl -n {{ namespace }} get pods -l app=nginx -o jsonpath='{.items[0].metadata.name}') -- nginx -s reload'"
        special_time: daily
      become: true

    - name: 测试自动续期
      shell: certbot renew --dry-run
      become: true 