---
- name: 安装 Kubernetes Event Exporter
  hosts: all
  gather_facts: no
  tasks:
    - name: 创建 Event Exporter 配置
      copy:
        dest: /tmp/event-exporter.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: event-exporter
            namespace: kube-system
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: event-exporter
            template:
              metadata:
                labels:
                  app: event-exporter
              spec:
                containers:
                - name: event-exporter
                  image: ghcr.io/opsgenie/kubernetes-event-exporter:v0.11
                  args:
                    - -conf=/data/config.yaml
                  volumeMounts:
                    - name: config
                      mountPath: /data
                volumes:
                - name: config
                  configMap:
                    name: event-exporter-cfg
          ---
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: event-exporter-cfg
            namespace: kube-system
          data:
            config.yaml: |
              logLevel: error
              logFormat: json
              receivers:
                - name: "webhook"
                  webhook:
                    endpoint: "http://your-webhook-endpoint"  # 需要替换为实际的 webhook 地址
                    headers:
                      Content-Type: application/json
                    layout:
                      text: |
                        【K3s 集群通知】
                        事件类型: {{ .Type }}
                        资源: {{ .InvolvedObject.Kind }}/{{ .InvolvedObject.Name }}
                        命名空间: {{ .Namespace }}
                        原因: {{ .Reason }}
                        消息: {{ .Message }}
                        时间: {{ .LastTimestamp }}
              route:
                routes:
                  - match:
                      - type: "Warning"
                    receivers:
                      - "webhook"
                  - match:
                      - type: "Normal"
                        reason: "Failed"
                    receivers:
                      - "webhook"

    - name: 应用 Event Exporter 配置
      shell: |
        echo "=== 部署 Event Exporter ==="
        /usr/local/bin/k3s kubectl apply -f /tmp/event-exporter.yaml
      register: deploy_result

    - name: 显示部署结果
      debug:
        msg: "{{ deploy_result.stdout_lines | default([]) }}" 