---
- name: 安装 Certbot
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('magento-shared') }}"  # 默认使用共享命名空间
    email: "{{ certbot_email }}"  # 需要通过 -e "certbot_email=your@email.com" 指定
    domains: "{{ certbot_domains }}"  # 需要通过 -e "certbot_domains=['domain1.com','domain2.com']" 指定

  tasks:
    - name: 获取 Nginx Pod 名称
      shell: |
        set -x
        POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=nginx -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$POD_NAME" ]; then
          echo "未找到 Nginx Pod"
          exit 1
        fi
        echo $POD_NAME
      register: pod_name

    - name: 安装 Certbot
      shell: |
        set -x
        POD_NAME="{{ pod_name.stdout }}"
        echo "=== 安装 Certbot ==="
        
        # 在 Nginx Pod 中安装 Certbot
        kubectl exec -n {{ use_namespace }} $POD_NAME -- bash -c '
          # 安装依赖
          apt-get update
          apt-get install -y python3-pip
          
          # 安装 certbot
          pip3 install certbot certbot-nginx
          
          # 验证安装
          certbot --version
        '
      register: install_result

    - name: 显示安装结果
      debug:
        msg: "{{ install_result.stdout_lines }}"

    - name: 申请证书
      shell: |
        set -x
        POD_NAME="{{ pod_name.stdout }}"
        echo "=== 申请 SSL 证书 ==="
        
        # 在 Nginx Pod 中申请证书
        kubectl exec -n {{ use_namespace }} $POD_NAME -- certbot --nginx \
          --non-interactive \
          --agree-tos \
          --email {{ email }} \
          {% for domain in domains %}
          -d {{ domain }} \
          {% endfor %}
          --redirect
      register: cert_result
      when: email is defined and domains is defined

    - name: 显示证书申请结果
      debug:
        msg: "{{ cert_result.stdout_lines }}"
      when: email is defined and domains is defined 