---
- name: 安装 PHP-FPM 基础扩展（第一批）
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('default') }}"

  tasks:
    - name: 获取 PHP-FPM Pod 名称
      shell: |
        POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=php-fpm -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$POD_NAME" ]; then
          echo "未找到 PHP-FPM Pod"
          exit 1
        fi
        echo $POD_NAME
      register: pod_name

    - name: 安装基础扩展
      shell: |
        POD_NAME="{{ pod_name.stdout }}"
        echo "=== 开始安装基础扩展 ==="
        
        # 更新包管理器
        echo "更新包管理器..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- apt-get update
        
        # 安装依赖
        echo "安装依赖..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- apt-get install -y \
          libicu-dev \
          libzip-dev
        
        # 安装扩展
        echo "安装 PDO MySQL 扩展..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- docker-php-ext-install pdo_mysql
        
        echo "安装 JSON 扩展..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- docker-php-ext-install json
        
        echo "安装 OPcache 扩展..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- docker-php-ext-install opcache
        
        # 配置 OPcache
        echo "配置 OPcache..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- /bin/sh -c 'echo "
        opcache.enable=1
        opcache.memory_consumption=256
        opcache.max_accelerated_files=60000
        opcache.revalidate_freq=2
        opcache.save_comments=1
        " > /usr/local/etc/php/conf.d/opcache.ini'
        
        # 验证扩展安装
        echo "验证扩展安装..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- php -m
        
        # 重启 PHP-FPM
        echo "重启 PHP-FPM..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- kill -USR2 1
      register: install_result

    - name: 显示安装结果
      debug:
        msg: "{{ install_result.stdout_lines }}" 