---
- name: 安装 PHP-FPM 8.3
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('hawk') }}"
    use_nodeport: "{{ nodeport | default('30900') }}"
  tasks:
    - name: 创建命名空间
      shell: |
        if [ "{{ use_namespace }}" != "default" ]; then
          echo "=== 创建命名空间 {{ use_namespace }} ==="
          /usr/local/bin/k3s kubectl create namespace {{ use_namespace }} || true
        fi
      register: namespace_result

    - name: 创建 PHP-FPM 配置
      copy:
        dest: /tmp/php-fpm.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: php-fpm
            namespace: {{ use_namespace }}
            labels:
              app: php-fpm
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: php-fpm
            template:
              metadata:
                labels:
                  app: php-fpm
              spec:
                containers:
                - name: php-fpm
                  image: localhost:5000/magento-php-fpm:8.3
                  ports:
                  - containerPort: 9000
                    name: fpm
                  readinessProbe:
                    tcpSocket:
                      port: 9000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 3
                  livenessProbe:
                    tcpSocket:
                      port: 9000
                    initialDelaySeconds: 20
                    periodSeconds: 20
                    timeoutSeconds: 5
                    failureThreshold: 3
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "250m"
                    limits:
                      memory: "512Mi"
                      cpu: "500m"
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: php-fpm
            namespace: {{ use_namespace }}
            labels:
              app: php-fpm
          spec:
            type: NodePort
            ports:
            - port: 9000
              targetPort: 9000
              nodePort: {{ use_nodeport }}
              name: fpm
            selector:
              app: php-fpm

    - name: 清理旧的部署
      shell: |
        echo "=== 清理旧的部署 ==="
        /usr/local/bin/k3s kubectl delete -f /tmp/php-fpm.yaml || true
        echo "等待资源清理完成..."
        sleep 5
      register: cleanup_result

    - name: 应用 PHP-FPM 配置
      shell: |
        echo "=== 开始部署 PHP-FPM ==="
        /usr/local/bin/k3s kubectl apply -f /tmp/php-fpm.yaml
      register: apply_result

    - name: 等待 Pod 创建
      shell: |
        for i in $(seq 1 30); do
          echo "检查 Pod 创建进度... $i/30"
          if /usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=php-fpm 2>/dev/null | grep -q php-fpm; then
            echo "Pod 已创建"
            exit 0
          fi
          sleep 2
        done
        echo "错误: Pod 未能成功创建"
        exit 1
      register: pod_creation_result

    - name: 等待 Pod 就绪
      shell: |
        for i in $(seq 1 60); do
          echo "检查 Pod 状态... $i/60"
          POD_NAME=$(/usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=php-fpm -o jsonpath='{.items[0].metadata.name}')
          if [ -z "$POD_NAME" ]; then
            echo "Pod 名称为空，继续等待..."
            sleep 5
            continue
          fi
          
          echo "Pod 名称: $POD_NAME"
          STATUS=$(/usr/local/bin/k3s kubectl get pod -n {{ use_namespace }} $POD_NAME -o jsonpath='{.status.phase}')
          echo "Pod 状态: $STATUS"
          
          if [ "$STATUS" = "Running" ]; then
            READY=$(/usr/local/bin/k3s kubectl get pod -n {{ use_namespace }} $POD_NAME -o jsonpath='{.status.containerStatuses[0].ready}')
            echo "Pod Ready 状态: $READY"
            
            if [ "$READY" = "true" ]; then
              echo "Pod 已就绪"
              exit 0
            fi
          fi
          
          echo "=== Pod 详细信息 ==="
          /usr/local/bin/k3s kubectl describe pod -n {{ use_namespace }} $POD_NAME
          
          echo "=== Pod 日志 ==="
          /usr/local/bin/k3s kubectl logs -n {{ use_namespace }} $POD_NAME --tail=50 || true
          
          sleep 5
        done
        echo "错误: Pod 未能在预期时间内就绪"
        exit 1
      register: pod_ready_result

    - name: 显示部署状态
      shell: |
        echo -e "\n=== PHP-FPM 部署状态 ==="
        echo "Pod 状态:"
        /usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=php-fpm -o wide
        
        echo -e "\nService 状态:"
        /usr/local/bin/k3s kubectl get svc -n {{ use_namespace }} -l app=php-fpm
        
        echo -e "\n=== 访问地址 ==="
        NODE_IP=$(/usr/local/bin/k3s kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')
        echo "tcp://$NODE_IP:{{ use_nodeport }}"
      register: status_result

    - name: 显示部署结果
      debug:
        msg: 
          - "{{ namespace_result.stdout_lines | default([]) }}"
          - "{{ cleanup_result.stdout_lines | default([]) }}"
          - "{{ apply_result.stdout_lines | default([]) }}"
          - "{{ pod_creation_result.stdout_lines | default([]) }}"
          - "{{ pod_ready_result.stdout_lines | default([]) }}"
          - "{{ status_result.stdout_lines | default([]) }}" 