---
- name: 安装 Percona XtraBackup
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('magento') }}"
    k3s_bin: "/usr/local/bin/k3s"
  
  tasks:
    - name: 创建临时 Pod
      command: >
        {{ k3s_bin }} kubectl run xtrabackup-test 
        --image=percona/percona-xtrabackup:8.0 
        --restart=Never 
        -n {{ use_namespace }}
        -- sleep infinity
      register: pod_result
      ignore_errors: yes

    - name: 显示 Pod 创建结果
      debug:
        var: pod_result.stdout_lines

    - name: 等待 Pod 就绪
      command: "{{ k3s_bin }} kubectl wait --for=condition=Ready pod/xtrabackup-test -n {{ use_namespace }} --timeout=60s"
      register: wait_result

    - name: 显示等待结果
      debug:
        var: wait_result.stdout_lines

    - name: 检查 xtrabackup 版本
      command: "{{ k3s_bin }} kubectl exec -n {{ use_namespace }} xtrabackup-test -- xtrabackup --version"
      register: version_result

    - name: 显示版本信息
      debug:
        var: version_result.stdout_lines

    - name: 删除测试 Pod
      command: "{{ k3s_bin }} kubectl delete pod xtrabackup-test -n {{ use_namespace }}"
      register: delete_result
      ignore_errors: yes
      when: pod_result is success 