---
- name: 安装 Redis 7.2 (StatefulSet)
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('default') }}"
    use_memory: "{{ memory | default('1Gi') }}"
    use_storage: "{{ storage | default('10Gi') }}"
    use_nodeport: "{{ nodeport | default('30379') }}"
  tasks:
    - name: 创建命名空间
      shell: |
        if [ "{{ use_namespace }}" != "default" ]; then
          echo "=== 创建命名空间 {{ use_namespace }} ==="
          /usr/local/bin/k3s kubectl create namespace {{ use_namespace }} || true
        fi
      register: namespace_result

    - name: 创建 Redis 配置
      copy:
        dest: /tmp/redis-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: redis-config
            namespace: {{ use_namespace }}
          data:
            redis.conf: |
              # 基础配置
              port 6379
              bind 0.0.0.0
              protected-mode no
              daemonize no
              supervised no
              
              # 内存配置
              maxmemory {{ use_memory }}
              maxmemory-policy allkeys-lru
              
              # 持久化配置
              dir /data
              appendonly yes
              appendfilename "appendonly.aof"
              appendfsync everysec
              
              # 数据库配置
              databases 16
              
              # 连接配置
              timeout 0
              tcp-keepalive 300
              
              # 日志配置
              loglevel notice
              logfile ""
              
              # 安全配置
              rename-command FLUSHALL ""
              rename-command FLUSHDB ""
              rename-command DEBUG ""

    - name: 创建 Redis StatefulSet
      copy:
        dest: /tmp/redis-statefulset.yaml
        content: |
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: redis
            namespace: {{ use_namespace }}
            labels:
              app: redis
          spec:
            serviceName: redis
            replicas: 1
            selector:
              matchLabels:
                app: redis
            template:
              metadata:
                labels:
                  app: redis
              spec:
                securityContext:
                  runAsUser: 999
                  runAsGroup: 999
                  fsGroup: 999
                containers:
                - name: redis
                  image: redis:7.2
                  args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
                  ports:
                  - name: redis
                    containerPort: 6379
                  resources:
                    requests:
                      memory: {{ use_memory }}
                      cpu: "0.5"
                    limits:
                      memory: {{ use_memory }}
                      cpu: "1"
                  volumeMounts:
                  - name: redis-config
                    mountPath: /usr/local/etc/redis/redis.conf
                    subPath: redis.conf
                  - name: redis-data
                    mountPath: /data
                  livenessProbe:
                    tcpSocket:
                      port: redis
                    initialDelaySeconds: 30
                    periodSeconds: 10
                    timeoutSeconds: 5
                  readinessProbe:
                    tcpSocket:
                      port: redis
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    timeoutSeconds: 5
                volumes:
                - name: redis-config
                  configMap:
                    name: redis-config
                    defaultMode: 0644
            volumeClaimTemplates:
            - metadata:
                name: redis-data
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: {{ use_storage }}
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: redis
            namespace: {{ use_namespace }}
            labels:
              app: redis
          spec:
            type: NodePort
            ports:
            - name: redis
              port: 6379
              targetPort: redis
              nodePort: {{ use_nodeport }}
            selector:
              app: redis

    - name: 应用 Redis 配置
      shell: |
        echo "=== 应用 Redis 配置 ==="
        /usr/local/bin/k3s kubectl apply -f /tmp/redis-config.yaml -f /tmp/redis-statefulset.yaml
      register: apply_result

    - name: 等待 Pod 创建完成
      shell: |
        echo "=== 等待 Pod 创建完成 ==="
        
        # 等待 Pod 创建
        for i in $(seq 1 30); do
          POD_NAME=$(/usr/local/bin/k3s kubectl get pods -n {{ use_namespace }} -l app=redis -o jsonpath='{.items[0].metadata.name}')
          if [ ! -z "$POD_NAME" ]; then
            break
          fi
          echo "等待 Pod 创建... 第 $i 次尝试"
          sleep 5
        done
        
        if [ -z "$POD_NAME" ]; then
          echo "错误: Pod 未能创建"
          exit 1
        fi
        
        # 检查 Pod 状态
        echo "Pod 已创建: $POD_NAME"
        /usr/local/bin/k3s kubectl describe pod -n {{ use_namespace }} $POD_NAME
        
        # 检查 Pod 日志
        echo "Pod 日志:"
        /usr/local/bin/k3s kubectl logs -n {{ use_namespace }} $POD_NAME
        
        # 检查 PVC 状态
        echo "PVC 状态:"
        /usr/local/bin/k3s kubectl get pvc -n {{ use_namespace }}
        
        # 检查最终状态
        POD_STATUS=$(/usr/local/bin/k3s kubectl get pod $POD_NAME -n {{ use_namespace }} -o jsonpath='{.status.phase}')
        if [ "$POD_STATUS" != "Running" ]; then
          echo "错误: Pod 未能正常运行，状态: $POD_STATUS"
          exit 1
        fi
        
        echo "Pod 已成功启动"
      register: wait_result 