---
- name: 安装 Composer 2.7
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('magento-shared') }}"  # 默认使用共享命名空间

  tasks:
    - name: 获取 PHP-FPM Pod 名称
      shell: |
        set -x  # 启用调试模式
        POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=php-fpm,role=shared -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$POD_NAME" ]; then
          echo "未找到共享 PHP-FPM Pod"
          exit 1
        fi
        echo $POD_NAME
      register: pod_name

    - name: 检查 Pod 状态
      shell: |
        set -x  # 启用调试模式
        POD_NAME="{{ pod_name.stdout }}"
        echo "检查 Pod $POD_NAME 状态..."
        
        # 显示 Pod 详细信息
        echo "Pod 详细信息:"
        kubectl describe pod -n {{ use_namespace }} $POD_NAME
        
        # 检查 Pod 状态
        STATUS=$(kubectl get pod -n {{ use_namespace }} $POD_NAME -o jsonpath='{.status.phase}')
        echo "Pod 状态: $STATUS"
        
        if [ "$STATUS" != "Running" ]; then
          echo "Pod 未处于运行状态"
          exit 1
        fi
      register: pod_status

    - name: 显示 Pod 状态
      debug:
        msg: "{{ pod_status.stdout_lines }}"

    - name: 安装 Composer
      shell: |
        set -x  # 启用调试模式
        set -e  # 遇到错误就退出
        POD_NAME="{{ pod_name.stdout }}"
        echo "=== 安装 Composer ==="
        
        echo "检查当前用户..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- whoami
        
        echo "更新包管理器..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- apt-get update
        
        echo "安装依赖..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- apt-get install -y unzip git curl ca-certificates
        
        echo "下载 Composer 安装脚本..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
        
        echo "验证下载..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- ls -l /tmp/composer-setup.php
        
        echo "安装 Composer 2.7..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=2.7.1
        
        echo "验证安装..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- ls -l /usr/local/bin/composer
        
        echo "设置权限..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- chmod +x /usr/local/bin/composer
        
        echo "清理安装文件..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- rm -f /tmp/composer-setup.php
        
        echo "验证 Composer 版本..."
        kubectl exec -n {{ use_namespace }} $POD_NAME -- composer --version
      register: install_result

    - name: 显示安装结果
      debug:
        msg: "{{ install_result.stdout_lines }}" 