---
- name: 安装和配置 K3s
  hosts: all
  gather_facts: yes
  tasks:
    - name: 安装 K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: 等待服务启动
      pause:
        seconds: 20
      
    - name: 创建 .kube 目录
      file:
        path: ~/.kube
        state: directory
        mode: '0755'

    - name: 复制 K3s 配置文件
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        remote_src: yes
        mode: '0600'
      become: yes

    - name: 修改配置文件所有权
      file:
        path: ~/.kube/config
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      become: yes

    - name: 验证安装
      shell: |
        echo "=== 节点状态 ==="
        kubectl get nodes
        
        echo -e "\n=== 系统 Pod 状态 ==="
        kubectl get pods -A
      register: k3s_status
      
    - name: 显示安装结果
      debug:
        msg: "{{ k3s_status.stdout_lines | default([]) }}" 