---
- name: 安装 Composer 2.7
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('magento-shared') }}"  # 默认使用共享命名空间

  tasks:
    - name: 获取 PHP-FPM Pod 名称
      shell: |
        set -x  # 启用调试模式
        POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=php-fpm,role=shared -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$POD_NAME" ]; then
          echo "未找到共享 PHP-FPM Pod"
          exit 1
        fi
        echo $POD_NAME
      register: pod_name

    - name: 检查 Pod 状态
      shell: |
        set -x  # 启用调试模式
        POD_NAME="{{ pod_name.stdout }}"
        echo "检查 Pod $POD_NAME 状态..."
        
        # 显示 Pod 详细信息
        echo "Pod 详细信息:"
        kubectl describe pod -n {{ use_namespace }} $POD_NAME
        
        # 检查 Pod 状态
        STATUS=$(kubectl get pod -n {{ use_namespace }} $POD_NAME -o jsonpath='{.status.phase}')
        echo "Pod 状态: $STATUS"
        
        if [ "$STATUS" != "Running" ]; then
          echo "Pod 未处于运行状态"
          exit 1
        fi
      register: pod_status

    - name: 显示 Pod 状态
      debug:
        msg: "{{ pod_status.stdout_lines }}"

    - name: 安装 Composer
      shell: |
        set -x  # 启用调试模式
        set -e  # 遇到错误就退出
        POD_NAME="{{ pod_name.stdout }}"
        echo "=== 安装 Composer ==="
        
        # 切换到 root 用户并执行命令
        kubectl exec -n {{ use_namespace }} $POD_NAME -- bash << 'EOF'
        set -x  # 启用调试模式
        set -e  # 遇到错误就退出
        
        # 检查当前用户
        echo "当前用户:"
        whoami
        
        # 安装依赖
        echo "安装依赖..."
        apt-get update
        apt-get install -y \
          unzip \
          git \
          curl \
          ca-certificates
        
        # 下载 Composer 安装脚本
        echo "下载 Composer 安装脚本..."
        curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
        
        # 验证下载是否成功
        if [ ! -f /tmp/composer-setup.php ]; then
          echo "下载 Composer 安装脚本失败"
          exit 1
        fi
        
        # 安装指定版本的 Composer
        echo "安装 Composer 2.7..."
        php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=2.7.1
        
        # 验证 composer 文件是否存在
        if [ ! -f /usr/local/bin/composer ]; then
          echo "Composer 安装失败"
          exit 1
        fi
        
        # 设置执行权限
        chmod +x /usr/local/bin/composer
        
        # 清理安装文件
        rm -f /tmp/composer-setup.php
        
        # 验证安装
        echo "验证 Composer 安装..."
        composer --version
        EOF
      register: install_result

    - name: 显示安装结果
      debug:
        msg: "{{ install_result.stdout_lines }}" 