---
- name: 检查已安装的服务
  hosts: all
  vars:
    namespace: "{{ namespace | default('default') }}"
  
  tasks:
    - name: 获取所有资源
      shell: |
        echo "=== Pods 状态 ==="
        /usr/local/bin/k3s kubectl get pods -n {{ namespace }}
        
        echo -e "\n=== Services 状态 ==="
        /usr/local/bin/k3s kubectl get services -n {{ namespace }}
        
        echo -e "\n=== Deployments 状态 ==="
        /usr/local/bin/k3s kubectl get deployments -n {{ namespace }}
        
        echo -e "\n=== 访问地址 ==="
        NODE_IP=$(/usr/local/bin/k3s kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')
        /usr/local/bin/k3s kubectl get svc -n {{ namespace }} -o jsonpath='{range .items[*]}{.metadata.name}{" -> http://"}{env.NODE_IP}{":" }{.spec.ports[0].nodePort}{"\n"}{end}'
      register: resources

    - name: 显示资源状态
      debug:
        var: resources.stdout_lines 