---
- name: 测试 AWX 和 K3s 连接
  hosts: all
  gather_facts: no
  tasks:
    - name: 检查基本连接
      shell: |
        echo "=== 用户信息 ==="
        id
        whoami
        echo "当前目录: $(pwd)"
        env | grep -i user
        
        echo -e "\n=== K3s 文件权限 ==="
        ls -l /usr/local/bin/k3s
        ls -l /etc/rancher/k3s/k3s.yaml || echo "k3s.yaml 不存在"
        
        echo -e "\n=== K3s 状态 ==="
        /usr/local/bin/k3s kubectl get node
        /usr/local/bin/k3s kubectl get pods -A
      register: connection_info

    - name: 显示连接信息
      debug:
        msg: "{{ connection_info.stdout_lines | default([]) }}"

    - name: 检查 K3s 状态
      shell: |
        echo "=== K3s 节点状态 ==="
        /usr/local/bin/k3s kubectl get nodes
        
        echo -e "\n=== K3s 系统 Pod ==="
        /usr/local/bin/k3s kubectl get pods -n kube-system
        
        echo -e "\n=== K3s 存储类 ==="
        /usr/local/bin/k3s kubectl get storageclass
        
        echo -e "\n=== K3s 版本信息 ==="
        /usr/local/bin/k3s --version
      register: k3s_info

    - name: 显示 K3s 信息
      debug:
        msg: "{{ k3s_info.stdout_lines | default([]) }}" 