---
- name: 卸载 PHP-FPM
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('default') }}"

  tasks:
    - name: 显示卸载信息
      debug:
        msg: "准备从命名空间 {{ use_namespace }} 卸载 PHP-FPM"

    - name: 强制删除 PHP-FPM 资源
      shell: |
        set -x
        echo "=== 开始卸载 PHP-FPM ==="
        
        # 强制删除 Pod
        echo "强制删除 Pod..."
        kubectl delete pod -n {{ use_namespace }} -l app=php-fpm --force --grace-period=0 || true
        
        # 删除 Service
        echo "删除 Service..."
        kubectl delete service -n {{ use_namespace }} php-fpm --force --grace-period=0 || true
        
        # 删除 Deployment
        echo "删除 Deployment..."
        kubectl delete deployment -n {{ use_namespace }} php-fpm --force --grace-period=0 || true
        
        # 删除 ConfigMap
        echo "删除 ConfigMap..."
        kubectl delete configmap -n {{ use_namespace }} -l app=php-fpm --force --grace-period=0 || true
        
        # 删除 PVC
        echo "删除 PVC..."
        kubectl delete pvc -n {{ use_namespace }} -l app=php-fpm --force --grace-period=0 || true
        
        # 等待资源清理完成
        echo "等待资源清理完成..."
        sleep 10
        
        # 强制删除卡住的 Pod
        echo "检查是否有卡住的 Pod..."
        STUCK_PODS=$(kubectl get pods -n {{ use_namespace }} -l app=php-fpm -o jsonpath='{.items[*].metadata.name}' || true)
        if [ ! -z "$STUCK_PODS" ]; then
          echo "发现卡住的 Pod，强制删除..."
          for pod in $STUCK_PODS; do
            kubectl delete pod -n {{ use_namespace }} $pod --force --grace-period=0 || true
          done
        fi
        
        # 再次等待清理完成
        echo "等待最终清理完成..."
        sleep 5
        
        echo -e "\n=== 清理结果 ==="
        echo "Pod 状态:"
        kubectl get pods -n {{ use_namespace }} -l app=php-fpm
        echo -e "\nService 状态:"
        kubectl get service -n {{ use_namespace }} php-fpm
        echo -e "\nDeployment 状态:"
        kubectl get deployment -n {{ use_namespace }} php-fpm
        echo -e "\nConfigMap 状态:"
        kubectl get configmap -n {{ use_namespace }} -l app=php-fpm
        echo -e "\nPVC 状态:"
        kubectl get pvc -n {{ use_namespace }} -l app=php-fpm
      register: cleanup_result

    - name: 显示清理结果
      debug:
        msg: "{{ cleanup_result.stdout_lines }}"

    - name: 清理命名空间（如果为空）
      shell: |
        set -x
        echo "=== 检查命名空间是否为空 ==="
        
        # 检查命名空间中的资源
        RESOURCES=$(kubectl get all -n {{ use_namespace }} -o name || true)
        if [ -z "$RESOURCES" ]; then
          echo "命名空间为空，删除命名空间..."
          kubectl delete namespace {{ use_namespace }} || true
        else
          echo "命名空间不为空，保留命名空间"
          echo "剩余资源:"
          echo "$RESOURCES"
        fi
      register: namespace_cleanup_result

    - name: 显示命名空间清理结果
      debug:
        msg: "{{ namespace_cleanup_result.stdout_lines }}"

    - name: 清理 PHP 包
      shell: |
        set -x
        echo "=== 清理 PHP 包 ==="
        
        # 获取 Pod 名称
        POD_NAME=$(kubectl get pods -n {{ use_namespace }} -l app=php-fpm -o jsonpath='{.items[0].metadata.name}' || true)
        
        if [ ! -z "$POD_NAME" ]; then
          echo "清理 PHP 包..."
          kubectl exec -n {{ use_namespace }} $POD_NAME -- bash -c '
            # 停止 PHP-FPM 服务
            service php8.3-fpm stop || true
            systemctl stop php8.3-fpm || true
            
            # 卸载所有 PHP 8.3 包
            apt-get remove -y php8.3-* || true
            apt-get purge -y php8.3-* || true
            apt-get autoremove -y || true
            
            # 清理配置文件
            rm -rf /etc/php/8.3 || true
            rm -rf /var/lib/php/modules/8.3 || true
            rm -rf /var/lib/php/sessions || true
            
            # 清理 PHP 仓库
            rm -f /etc/apt/sources.list.d/php.list || true
            rm -f /etc/apt/trusted.gpg.d/php.gpg || true
            
            # 更新包列表
            apt-get update -y || true
          '
        else
          echo "未找到 PHP-FPM Pod，跳过包清理"
        fi
      register: cleanup_php_result

    - name: 显示包清理结果
      debug:
        msg: "{{ cleanup_php_result.stdout_lines }}" 