---
- name: 卸载 Nginx
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('default') }}"  # 默认使用 default 命名空间

  tasks:
    - name: 显示卸载信息
      debug:
        msg: "准备从命名空间 {{ use_namespace }} 卸载 Nginx"

    - name: 卸载 Nginx
      shell: |
        set -x
        echo "=== 开始卸载命名空间 {{ use_namespace }} 中的 Nginx ==="
        
        echo "强制删除 Pod..."
        kubectl delete pod -n {{ use_namespace }} -l app=nginx --force --grace-period=0 || true
        
        echo "删除 Deployment..."
        kubectl delete deployment -n {{ use_namespace }} -l app=nginx || true
        
        echo "删除 Service..."
        kubectl delete service -n {{ use_namespace }} -l app=nginx || true
        
        echo "删除 ConfigMap..."
        kubectl delete configmap -n {{ use_namespace }} -l app=nginx || true
        
        echo "等待资源清理完成..."
        sleep 5
        
        echo "验证清理结果..."
        kubectl get all -n {{ use_namespace }} -l app=nginx
      register: uninstall_result

    - name: 显示卸载结果
      debug:
        msg: "{{ uninstall_result.stdout_lines }}" 