---
- name: 卸载 PHP-FPM
  hosts: all
  gather_facts: no
  vars:
    use_namespace: "{{ namespace | default('default') }}"

  tasks:
    - name: 显示卸载信息
      debug:
        msg: "准备从命名空间 {{ use_namespace }} 卸载 PHP-FPM"

    - name: 强制删除 PHP-FPM Pod
      shell: |
        set -x
        echo "=== 开始卸载 PHP-FPM ==="
        
        # 获取 k3s 路径
        K3S_PATH=$(which k3s || echo "/usr/local/bin/k3s")
        
        # 强制删除 Pod
        $K3S_PATH kubectl delete pod -n {{ use_namespace }} -l app=php-fpm --force --grace-period=0 || true
        
        # 删除 Deployment
        $K3S_PATH kubectl delete deployment -n {{ use_namespace }} php-fpm || true
        
        # 删除 Service
        $K3S_PATH kubectl delete service -n {{ use_namespace }} php-fpm || true
        
        echo "等待资源清理完成..."
        sleep 5
        
        echo -e "\n=== 清理结果 ==="
        echo "Pod 状态:"
        $K3S_PATH kubectl get pods -n {{ use_namespace }} -l app=php-fpm
        echo -e "\nDeployment 状态:"
        $K3S_PATH kubectl get deployment -n {{ use_namespace }} php-fpm
        echo -e "\nService 状态:"
        $K3S_PATH kubectl get service -n {{ use_namespace }} php-fpm
      register: cleanup_result

    - name: 显示清理结果
      debug:
        msg: "{{ cleanup_result.stdout_lines }}" 