---
- name: 配置 PHP-FPM Pool
  hosts: localhost
  connection: local
  vars:
    site_name: "{{ site_name }}"
    php_fpm_ns: "{{ php_fpm_ns }}"
    php_ini_config: |
      ; PHP 基础设置
      memory_limit = 4G
      max_execution_time = 300
      max_input_time = 300
      post_max_size = 64M
      upload_max_filesize = 64M
      max_input_vars = 10000
      
      ; 错误处理
      display_errors = Off
      display_startup_errors = Off
      error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
      log_errors = On
      error_log = /proc/self/fd/2
      
      ; 性能优化
      opcache.enable = 1
      opcache.memory_consumption = 512
      opcache.max_accelerated_files = 60000
      opcache.revalidate_freq = 0
      realpath_cache_size = 4096K
      realpath_cache_ttl = 600
      
      ; 时区设置
      date.timezone = Asia/Shanghai
      
      ; Session 配置
      session.save_handler = redis
      session.save_path = "tcp://redis:6379/1"
      session.gc_maxlifetime = 86400

    php_fpm_main_config: |
      [global]
      pid = /var/run/php-fpm.pid
      error_log = /proc/self/fd/2
      log_level = notice
      daemonize = no
      include=/usr/local/etc/php-fpm.d/*.conf
    
    php_fpm_pool_config: |
      [www]
      ; 用户和组配置
      user = www-data
      group = www-data

      ; 监听配置
      listen = 9000
      
      ; 进程管理
      pm = dynamic
      pm.max_children = 30
      pm.start_servers = 5
      pm.min_spare_servers = 3
      pm.max_spare_servers = 10
      pm.max_requests = 500

      ; 状态页
      pm.status_path = /status
      ping.path = /ping
      ping.response = pong

      ; 日志设置
      access.log = /proc/self/fd/2
      access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"
      catch_workers_output = yes
      decorate_workers_output = no

      ; 慢查询日志
      slowlog = /proc/self/fd/2
      request_slowlog_timeout = 10s
  
  tasks:
    - name: 创建 PHP-FPM 配置 ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ site_name }}-php-fpm-config"
            namespace: "{{ php_fpm_ns }}"
          data:
            "php-fpm.conf": "{{ php_fpm_main_config }}"
            "www.conf": "{{ php_fpm_pool_config }}"

    - name: 创建 PHP 配置 ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ site_name }}-php-config"
            namespace: "{{ php_fpm_ns }}"
          data:
            "php.ini": "{{ php_ini_config }}"

    - name: 更新 PHP-FPM Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: php-fpm
            namespace: "{{ php_fpm_ns }}"
          spec:
            replicas: 1
            strategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: 1
                maxUnavailable: 0
            selector:
              matchLabels:
                app: php-fpm
            template:
              metadata:
                labels:
                  app: php-fpm
              spec:
                volumes:
                - name: php-fpm-config
                  configMap:
                    name: "{{ site_name }}-php-fpm-config"
                - name: php-config
                  configMap:
                    name: "{{ site_name }}-php-config"
                containers:
                - name: php-fpm
                  image: php:8.3-fpm
                  imagePullPolicy: IfNotPresent
                  command: ["php-fpm"]
                  args: ["-F", "-y", "/usr/local/etc/php-fpm.conf"]
                  ports:
                  - containerPort: 9000
                    name: fpm
                  resources:
                    requests:
                      cpu: 500m
                      memory: 512Mi
                    limits:
                      cpu: 2000m
                      memory: 4Gi
                  livenessProbe:
                    tcpSocket:
                      port: 9000
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  readinessProbe:
                    tcpSocket:
                      port: 9000
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  volumeMounts:
                  - name: php-fpm-config
                    mountPath: "/usr/local/etc/php-fpm.conf"
                    subPath: "php-fpm.conf"
                  - name: php-fpm-config
                    mountPath: "/usr/local/etc/php-fpm.d/www.conf"
                    subPath: "www.conf"
                  - name: php-config
                    mountPath: "/usr/local/etc/php/conf.d/99-chen.ini"
                    subPath: "php.ini"
                  securityContext:
                    runAsUser: 33  # www-data
                    runAsGroup: 33
                    allowPrivilegeEscalation: false 