---
- name: 配置 PHP-FPM Pool
  hosts: localhost
  connection: local
  vars:
    site_name: "{{ site_name }}"
    php_fpm_ns: "{{ php_fpm_ns }}"
    config_filename: "chen.conf"
    php_ini_config: |
      memory_limit = 4G
      max_execution_time = 300
      max_input_time = 300
      post_max_size = 64M
      upload_max_filesize = 64M
      date.timezone = Asia/Shanghai
      opcache.enable = 1
      opcache.memory_consumption = 512
      opcache.max_accelerated_files = 60000
      opcache.revalidate_freq = 0
      realpath_cache_size = 4096K
      realpath_cache_ttl = 600
      max_input_vars = 10000
      display_errors = Off
      display_startup_errors = Off
      error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
    php_fpm_config: |
      [chen]
      ; 用户和组配置
      user = www-data
      group = www-data

      ; 监听配置
      listen = 9000
      
      ; 进程管理
      pm = dynamic
      pm.max_children = 30
      pm.start_servers = 5
      pm.min_spare_servers = 3
      pm.max_spare_servers = 10
      pm.max_requests = 500

      ; 日志设置
      access.log = /proc/self/fd/2
      access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"
      catch_workers_output = yes
      decorate_workers_output = no

      ; 慢查询日志
      slowlog = /proc/self/fd/2
      request_slowlog_timeout = 10s

      ; 站点特定设置
      php_admin_value[error_log] = /proc/self/fd/2
      php_admin_flag[log_errors] = on

      ; PHP 设置
      php_admin_value[memory_limit] = 4G
      php_admin_value[max_execution_time] = 300
      php_admin_value[max_input_time] = 300
      php_admin_value[post_max_size] = 64M
      php_admin_value[upload_max_filesize] = 64M

      ; 站点特定设置
      php_admin_value[date.timezone] = Asia/Shanghai

      ; Magento 2 优化设置
      php_admin_value[opcache.enable] = 1
      php_admin_value[opcache.memory_consumption] = 512
      php_admin_value[opcache.max_accelerated_files] = 60000
      php_admin_value[opcache.revalidate_freq] = 0
      php_admin_value[realpath_cache_size] = 4096K
      php_admin_value[realpath_cache_ttl] = 600

      ; Session 配置
      php_admin_value[session.save_handler] = redis
      php_admin_value[session.save_path] = "tcp://redis:6379/1"
      php_admin_value[session.gc_maxlifetime] = 86400

      ; 其他 PHP 设置
      php_admin_value[max_input_vars] = 10000
      php_admin_flag[display_errors] = off
      php_admin_flag[display_startup_errors] = off
      php_admin_value[error_reporting] = E_ALL & ~E_DEPRECATED & ~E_STRICT
  
  tasks:
    - name: 创建 ConfigMap for PHP-FPM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ site_name }}-php-fpm-config"
            namespace: "{{ php_fpm_ns }}"
          data:
            "chen.conf": "{{ php_fpm_config }}"
            "php.ini": "{{ php_ini_config }}"

    - name: 更新 PHP-FPM Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: php-fpm
            namespace: "{{ php_fpm_ns }}"
          spec:
            template:
              spec:
                volumes:
                - name: php-fpm-config
                  configMap:
                    name: "{{ site_name }}-php-fpm-config"
                containers:
                - name: php-fpm
                  volumeMounts:
                  - name: php-fpm-config
                    mountPath: "/usr/local/etc/php-fpm.d/chen.conf"
                    subPath: "chen.conf"
                  - name: php-fpm-config
                    mountPath: "/usr/local/etc/php/conf.d/99-chen.ini"
                    subPath: "php.ini" 